# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v2.x
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    paths:
      - tools
    rules:
      - path: _test\.go
        linters:
          - errcheck
