# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v2.x
version: "2"

run:
  timeout: 5m

linters:
  default: none
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
  exclusions:
    paths:
      - tools
    rules:
      - path: _test\.go
        linters:
          - errcheck

# Formatters configuration (golangci-lint v2.x)
# Run with: golangci-lint fmt --diff (check) or golangci-lint fmt (fix)
formatters:
  enable:
    - gofmt
  exclusions:
    # Temporarily exclude generated files until CI regenerates them with gofmt formatting.
    # TODO: Remove these exclusions after the regeneration PR is merged.
    # See: https://github.com/robinmordasiewicz/terraform-provider-f5xc/issues/321
    paths:
      - internal/provider/.*_resource\.go
      - internal/provider/.*_data_source\.go
      - internal/provider/.*_resource_test\.go
      - internal/provider/.*_data_source_test\.go
      - internal/provider/provider\.go
  settings:
    gofmt:
      # Simplify code: gofmt with -s option
      simplify: true
