# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/

run:
  timeout: 5m

issues:
  # Exclude the tools directory - contains standalone scripts with multiple main functions
  exclude-dirs:
    - tools
  # Exclude some linters from running on test files
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - dupl

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
