# golangci-lint configuration
# https://golangci-lint.run/usage/configuration/
# Compatible with golangci-lint v1.x

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  exclude-dirs:
    - tools
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
