// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// Authentication represents a F5XC Authentication
type Authentication struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateAuthentication creates a new Authentication
func (c *Client) CreateAuthentication(ctx context.Context, resource *Authentication) (*Authentication, error) {
	var result Authentication
	path := fmt.Sprintf("/api/config/namespaces/%s/authentications", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetAuthentication retrieves a Authentication
func (c *Client) GetAuthentication(ctx context.Context, namespace, name string) (*Authentication, error) {
	var result Authentication
	path := fmt.Sprintf("/api/config/namespaces/%s/authentications/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateAuthentication updates a Authentication
func (c *Client) UpdateAuthentication(ctx context.Context, resource *Authentication) (*Authentication, error) {
	var result Authentication
	path := fmt.Sprintf("/api/config/namespaces/%s/authentications/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteAuthentication deletes a Authentication
func (c *Client) DeleteAuthentication(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/authentications/%s", namespace, name)
	return c.Delete(ctx, path)
}
