// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// AWSTGWSite represents a F5XC AWSTGWSite
type AWSTGWSite struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateAWSTGWSite creates a new AWSTGWSite
func (c *Client) CreateAWSTGWSite(ctx context.Context, resource *AWSTGWSite) (*AWSTGWSite, error) {
	var result AWSTGWSite
	path := fmt.Sprintf("/api/config/namespaces/%s/aws_tgw_sites", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetAWSTGWSite retrieves a AWSTGWSite
func (c *Client) GetAWSTGWSite(ctx context.Context, namespace, name string) (*AWSTGWSite, error) {
	var result AWSTGWSite
	path := fmt.Sprintf("/api/config/namespaces/%s/aws_tgw_sites/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateAWSTGWSite updates a AWSTGWSite
func (c *Client) UpdateAWSTGWSite(ctx context.Context, resource *AWSTGWSite) (*AWSTGWSite, error) {
	var result AWSTGWSite
	path := fmt.Sprintf("/api/config/namespaces/%s/aws_tgw_sites/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteAWSTGWSite deletes a AWSTGWSite
func (c *Client) DeleteAWSTGWSite(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/aws_tgw_sites/%s", namespace, name)
	return c.Delete(ctx, path)
}
