// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// CloudElasticIP represents a F5XC CloudElasticIP
type CloudElasticIP struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateCloudElasticIP creates a new CloudElasticIP
func (c *Client) CreateCloudElasticIP(ctx context.Context, resource *CloudElasticIP) (*CloudElasticIP, error) {
	var result CloudElasticIP
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_elastic_ips", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetCloudElasticIP retrieves a CloudElasticIP
func (c *Client) GetCloudElasticIP(ctx context.Context, namespace, name string) (*CloudElasticIP, error) {
	var result CloudElasticIP
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_elastic_ips/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateCloudElasticIP updates a CloudElasticIP
func (c *Client) UpdateCloudElasticIP(ctx context.Context, resource *CloudElasticIP) (*CloudElasticIP, error) {
	var result CloudElasticIP
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_elastic_ips/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteCloudElasticIP deletes a CloudElasticIP
func (c *Client) DeleteCloudElasticIP(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/cloud_elastic_ips/%s", namespace, name)
	return c.Delete(ctx, path)
}
