// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// ContainerRegistry represents a F5XC ContainerRegistry
type ContainerRegistry struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateContainerRegistry creates a new ContainerRegistry
func (c *Client) CreateContainerRegistry(ctx context.Context, resource *ContainerRegistry) (*ContainerRegistry, error) {
	var result ContainerRegistry
	path := fmt.Sprintf("/api/config/namespaces/%s/container_registrys", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetContainerRegistry retrieves a ContainerRegistry
func (c *Client) GetContainerRegistry(ctx context.Context, namespace, name string) (*ContainerRegistry, error) {
	var result ContainerRegistry
	path := fmt.Sprintf("/api/config/namespaces/%s/container_registrys/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateContainerRegistry updates a ContainerRegistry
func (c *Client) UpdateContainerRegistry(ctx context.Context, resource *ContainerRegistry) (*ContainerRegistry, error) {
	var result ContainerRegistry
	path := fmt.Sprintf("/api/config/namespaces/%s/container_registrys/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteContainerRegistry deletes a ContainerRegistry
func (c *Client) DeleteContainerRegistry(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/container_registrys/%s", namespace, name)
	return c.Delete(ctx, path)
}
