// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// NetworkPolicyRule represents a F5XC NetworkPolicyRule
type NetworkPolicyRule struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateNetworkPolicyRule creates a new NetworkPolicyRule
func (c *Client) CreateNetworkPolicyRule(ctx context.Context, resource *NetworkPolicyRule) (*NetworkPolicyRule, error) {
	var result NetworkPolicyRule
	path := fmt.Sprintf("/api/config/namespaces/%s/network_policy_rules", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetNetworkPolicyRule retrieves a NetworkPolicyRule
func (c *Client) GetNetworkPolicyRule(ctx context.Context, namespace, name string) (*NetworkPolicyRule, error) {
	var result NetworkPolicyRule
	path := fmt.Sprintf("/api/config/namespaces/%s/network_policy_rules/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateNetworkPolicyRule updates a NetworkPolicyRule
func (c *Client) UpdateNetworkPolicyRule(ctx context.Context, resource *NetworkPolicyRule) (*NetworkPolicyRule, error) {
	var result NetworkPolicyRule
	path := fmt.Sprintf("/api/config/namespaces/%s/network_policy_rules/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteNetworkPolicyRule deletes a NetworkPolicyRule
func (c *Client) DeleteNetworkPolicyRule(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/network_policy_rules/%s", namespace, name)
	return c.Delete(ctx, path)
}
