// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// SecretPolicyRule represents a F5XC SecretPolicyRule
type SecretPolicyRule struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateSecretPolicyRule creates a new SecretPolicyRule
func (c *Client) CreateSecretPolicyRule(ctx context.Context, resource *SecretPolicyRule) (*SecretPolicyRule, error) {
	var result SecretPolicyRule
	path := fmt.Sprintf("/api/secret_management/namespaces/%s/secret_policy_rules", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetSecretPolicyRule retrieves a SecretPolicyRule
func (c *Client) GetSecretPolicyRule(ctx context.Context, namespace, name string) (*SecretPolicyRule, error) {
	var result SecretPolicyRule
	path := fmt.Sprintf("/api/secret_management/namespaces/%s/secret_policy_rules/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateSecretPolicyRule updates a SecretPolicyRule
func (c *Client) UpdateSecretPolicyRule(ctx context.Context, resource *SecretPolicyRule) (*SecretPolicyRule, error) {
	var result SecretPolicyRule
	path := fmt.Sprintf("/api/secret_management/namespaces/%s/secret_policy_rules/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteSecretPolicyRule deletes a SecretPolicyRule
func (c *Client) DeleteSecretPolicyRule(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/secret_management/namespaces/%s/secret_policy_rules/%s", namespace, name)
	return c.Delete(ctx, path)
}
