// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package client

import (
	"context"
	"fmt"
)

// TCPLoadBalancer represents a F5XC TCPLoadBalancer
type TCPLoadBalancer struct {
	Metadata Metadata               `json:"metadata"`
	Spec     map[string]interface{} `json:"spec"`
}

// CreateTCPLoadBalancer creates a new TCPLoadBalancer
func (c *Client) CreateTCPLoadBalancer(ctx context.Context, resource *TCPLoadBalancer) (*TCPLoadBalancer, error) {
	var result TCPLoadBalancer
	path := fmt.Sprintf("/api/config/namespaces/%s/tcp_loadbalancers", resource.Metadata.Namespace)
	err := c.Post(ctx, path, resource, &result)
	return &result, err
}

// GetTCPLoadBalancer retrieves a TCPLoadBalancer
func (c *Client) GetTCPLoadBalancer(ctx context.Context, namespace, name string) (*TCPLoadBalancer, error) {
	var result TCPLoadBalancer
	path := fmt.Sprintf("/api/config/namespaces/%s/tcp_loadbalancers/%s", namespace, name)
	err := c.Get(ctx, path, &result)
	return &result, err
}

// UpdateTCPLoadBalancer updates a TCPLoadBalancer
func (c *Client) UpdateTCPLoadBalancer(ctx context.Context, resource *TCPLoadBalancer) (*TCPLoadBalancer, error) {
	var result TCPLoadBalancer
	path := fmt.Sprintf("/api/config/namespaces/%s/tcp_loadbalancers/%s", resource.Metadata.Namespace, resource.Metadata.Name)
	err := c.Put(ctx, path, resource, &result)
	return &result, err
}

// DeleteTCPLoadBalancer deletes a TCPLoadBalancer
func (c *Client) DeleteTCPLoadBalancer(ctx context.Context, namespace, name string) error {
	path := fmt.Sprintf("/api/config/namespaces/%s/tcp_loadbalancers/%s", namespace, name)
	return c.Delete(ctx, path)
}
