// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc/terraform-provider-f5xc/internal/client"
	inttimeouts "github.com/f5xc/terraform-provider-f5xc/internal/timeouts"
	"github.com/f5xc/terraform-provider-f5xc/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &AppAPIGroupResource{}
	_ resource.ResourceWithConfigure      = &AppAPIGroupResource{}
	_ resource.ResourceWithImportState    = &AppAPIGroupResource{}
	_ resource.ResourceWithModifyPlan     = &AppAPIGroupResource{}
	_ resource.ResourceWithValidateConfig = &AppAPIGroupResource{}
)

func NewAppAPIGroupResource() resource.Resource {
	return &AppAPIGroupResource{}
}

type AppAPIGroupResource struct {
	client *client.Client
}

// AppAPIGroupEmptyModel represents empty nested blocks
type AppAPIGroupEmptyModel struct {
}

// AppAPIGroupBigIPVirtualServerModel represents bigip_virtual_server block
type AppAPIGroupBigIPVirtualServerModel struct {
	BigIPVirtualServer *AppAPIGroupBigIPVirtualServerBigIPVirtualServerModel `tfsdk:"bigip_virtual_server"`
}

// AppAPIGroupBigIPVirtualServerModelAttrTypes defines the attribute types for AppAPIGroupBigIPVirtualServerModel
var AppAPIGroupBigIPVirtualServerModelAttrTypes = map[string]attr.Type{
	"bigip_virtual_server": types.ObjectType{AttrTypes: AppAPIGroupBigIPVirtualServerBigIPVirtualServerModelAttrTypes},
}

// AppAPIGroupBigIPVirtualServerBigIPVirtualServerModel represents bigip_virtual_server block
type AppAPIGroupBigIPVirtualServerBigIPVirtualServerModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// AppAPIGroupBigIPVirtualServerBigIPVirtualServerModelAttrTypes defines the attribute types for AppAPIGroupBigIPVirtualServerBigIPVirtualServerModel
var AppAPIGroupBigIPVirtualServerBigIPVirtualServerModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

// AppAPIGroupCDNLoadBalancerModel represents cdn_loadbalancer block
type AppAPIGroupCDNLoadBalancerModel struct {
	CDNLoadBalancer *AppAPIGroupCDNLoadBalancerCDNLoadBalancerModel `tfsdk:"cdn_loadbalancer"`
}

// AppAPIGroupCDNLoadBalancerModelAttrTypes defines the attribute types for AppAPIGroupCDNLoadBalancerModel
var AppAPIGroupCDNLoadBalancerModelAttrTypes = map[string]attr.Type{
	"cdn_loadbalancer": types.ObjectType{AttrTypes: AppAPIGroupCDNLoadBalancerCDNLoadBalancerModelAttrTypes},
}

// AppAPIGroupCDNLoadBalancerCDNLoadBalancerModel represents cdn_loadbalancer block
type AppAPIGroupCDNLoadBalancerCDNLoadBalancerModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// AppAPIGroupCDNLoadBalancerCDNLoadBalancerModelAttrTypes defines the attribute types for AppAPIGroupCDNLoadBalancerCDNLoadBalancerModel
var AppAPIGroupCDNLoadBalancerCDNLoadBalancerModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

// AppAPIGroupElementsModel represents elements block
type AppAPIGroupElementsModel struct {
	Methods   types.List   `tfsdk:"methods"`
	PathRegex types.String `tfsdk:"path_regex"`
}

// AppAPIGroupElementsModelAttrTypes defines the attribute types for AppAPIGroupElementsModel
var AppAPIGroupElementsModelAttrTypes = map[string]attr.Type{
	"methods":    types.ListType{ElemType: types.StringType},
	"path_regex": types.StringType,
}

// AppAPIGroupHTTPLoadBalancerModel represents http_loadbalancer block
type AppAPIGroupHTTPLoadBalancerModel struct {
	HTTPLoadBalancer *AppAPIGroupHTTPLoadBalancerHTTPLoadBalancerModel `tfsdk:"http_loadbalancer"`
}

// AppAPIGroupHTTPLoadBalancerModelAttrTypes defines the attribute types for AppAPIGroupHTTPLoadBalancerModel
var AppAPIGroupHTTPLoadBalancerModelAttrTypes = map[string]attr.Type{
	"http_loadbalancer": types.ObjectType{AttrTypes: AppAPIGroupHTTPLoadBalancerHTTPLoadBalancerModelAttrTypes},
}

// AppAPIGroupHTTPLoadBalancerHTTPLoadBalancerModel represents http_loadbalancer block
type AppAPIGroupHTTPLoadBalancerHTTPLoadBalancerModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// AppAPIGroupHTTPLoadBalancerHTTPLoadBalancerModelAttrTypes defines the attribute types for AppAPIGroupHTTPLoadBalancerHTTPLoadBalancerModel
var AppAPIGroupHTTPLoadBalancerHTTPLoadBalancerModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

type AppAPIGroupResourceModel struct {
	Name               types.String                        `tfsdk:"name"`
	Namespace          types.String                        `tfsdk:"namespace"`
	Annotations        types.Map                           `tfsdk:"annotations"`
	Description        types.String                        `tfsdk:"description"`
	Disable            types.Bool                          `tfsdk:"disable"`
	Labels             types.Map                           `tfsdk:"labels"`
	ID                 types.String                        `tfsdk:"id"`
	Timeouts           timeouts.Value                      `tfsdk:"timeouts"`
	BigIPVirtualServer *AppAPIGroupBigIPVirtualServerModel `tfsdk:"bigip_virtual_server"`
	CDNLoadBalancer    *AppAPIGroupCDNLoadBalancerModel    `tfsdk:"cdn_loadbalancer"`
	Elements           types.List                          `tfsdk:"elements"`
	HTTPLoadBalancer   *AppAPIGroupHTTPLoadBalancerModel   `tfsdk:"http_loadbalancer"`
}

func (r *AppAPIGroupResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_app_api_group"
}

func (r *AppAPIGroupResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages app_api_group creates a new object in the storage backend for metadata.namespace. in F5 Distributed Cloud.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the App API Group. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the App API Group will be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"bigip_virtual_server": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: bigip_virtual_server, cdn_loadbalancer, http_loadbalancer] Set the scope of the API Group to a specific BIG-IP Virtual Server.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"bigip_virtual_server": schema.SingleNestedBlock{
						MarkdownDescription: "Type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
								Optional:            true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
				},
			},
			"cdn_loadbalancer": schema.SingleNestedBlock{
				MarkdownDescription: "Set the scope of the API Group to a specific CDN Loadbalancer.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"cdn_loadbalancer": schema.SingleNestedBlock{
						MarkdownDescription: "Type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
								Optional:            true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
				},
			},
			"elements": schema.ListNestedBlock{
				MarkdownDescription: "List of API group elements with methods and path regex for matching requests.",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"methods": schema.ListAttribute{
							MarkdownDescription: "[Enum: ANY|GET|HEAD|POST|PUT|DELETE|CONNECT|OPTIONS|TRACE|PATCH|COPY] List of method values to match the input request API method against. The match is considered to succeed if the input request API method is a member of the list. Possible values are `ANY`, `GET`, `HEAD`, `POST`, `PUT`, `DELETE`, `CONNECT`, `OPTIONS`, `TRACE`, `PATCH`, `COPY`. Defaults to `ANY`.",
							Optional:            true,
							ElementType:         types.StringType,
						},
						"path_regex": schema.StringAttribute{
							MarkdownDescription: "Regular expression to match the input request API path against. The match is considered to succeed if the input request API path matches the specified path regex.",
							Optional:            true,
						},
					},
				},
			},
			"http_loadbalancer": schema.SingleNestedBlock{
				MarkdownDescription: "Set the scope of the API Group to a specific HTTP Loadbalancer.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"http_loadbalancer": schema.SingleNestedBlock{
						MarkdownDescription: "Type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
								Optional:            true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
				},
			},
		},
	}
}

func (r *AppAPIGroupResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *AppAPIGroupResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data AppAPIGroupResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *AppAPIGroupResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the app_api_group from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan AppAPIGroupResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

func (r *AppAPIGroupResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data AppAPIGroupResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating app_api_group", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.AppAPIGroup{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.BigIPVirtualServer != nil {
		bigip_virtual_serverMap := make(map[string]interface{})
		if data.BigIPVirtualServer.BigIPVirtualServer != nil {
			bigip_virtual_serverNestedMap := make(map[string]interface{})
			if !data.BigIPVirtualServer.BigIPVirtualServer.Name.IsNull() && !data.BigIPVirtualServer.BigIPVirtualServer.Name.IsUnknown() {
				bigip_virtual_serverNestedMap["name"] = data.BigIPVirtualServer.BigIPVirtualServer.Name.ValueString()
			}
			if !data.BigIPVirtualServer.BigIPVirtualServer.Namespace.IsNull() && !data.BigIPVirtualServer.BigIPVirtualServer.Namespace.IsUnknown() {
				bigip_virtual_serverNestedMap["namespace"] = data.BigIPVirtualServer.BigIPVirtualServer.Namespace.ValueString()
			}
			if !data.BigIPVirtualServer.BigIPVirtualServer.Tenant.IsNull() && !data.BigIPVirtualServer.BigIPVirtualServer.Tenant.IsUnknown() {
				bigip_virtual_serverNestedMap["tenant"] = data.BigIPVirtualServer.BigIPVirtualServer.Tenant.ValueString()
			}
			bigip_virtual_serverMap["bigip_virtual_server"] = bigip_virtual_serverNestedMap
		}
		createReq.Spec["bigip_virtual_server"] = bigip_virtual_serverMap
	}
	if data.CDNLoadBalancer != nil {
		cdn_loadbalancerMap := make(map[string]interface{})
		if data.CDNLoadBalancer.CDNLoadBalancer != nil {
			cdn_loadbalancerNestedMap := make(map[string]interface{})
			if !data.CDNLoadBalancer.CDNLoadBalancer.Name.IsNull() && !data.CDNLoadBalancer.CDNLoadBalancer.Name.IsUnknown() {
				cdn_loadbalancerNestedMap["name"] = data.CDNLoadBalancer.CDNLoadBalancer.Name.ValueString()
			}
			if !data.CDNLoadBalancer.CDNLoadBalancer.Namespace.IsNull() && !data.CDNLoadBalancer.CDNLoadBalancer.Namespace.IsUnknown() {
				cdn_loadbalancerNestedMap["namespace"] = data.CDNLoadBalancer.CDNLoadBalancer.Namespace.ValueString()
			}
			if !data.CDNLoadBalancer.CDNLoadBalancer.Tenant.IsNull() && !data.CDNLoadBalancer.CDNLoadBalancer.Tenant.IsUnknown() {
				cdn_loadbalancerNestedMap["tenant"] = data.CDNLoadBalancer.CDNLoadBalancer.Tenant.ValueString()
			}
			cdn_loadbalancerMap["cdn_loadbalancer"] = cdn_loadbalancerNestedMap
		}
		createReq.Spec["cdn_loadbalancer"] = cdn_loadbalancerMap
	}
	if !data.Elements.IsNull() && !data.Elements.IsUnknown() {
		var elementsItems []AppAPIGroupElementsModel
		diags := data.Elements.ElementsAs(ctx, &elementsItems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(elementsItems) > 0 {
			var elementsList []map[string]interface{}
			for _, item := range elementsItems {
				itemMap := make(map[string]interface{})
				if !item.PathRegex.IsNull() && !item.PathRegex.IsUnknown() {
					itemMap["path_regex"] = item.PathRegex.ValueString()
				}
				elementsList = append(elementsList, itemMap)
			}
			createReq.Spec["elements"] = elementsList
		}
	}
	if data.HTTPLoadBalancer != nil {
		http_loadbalancerMap := make(map[string]interface{})
		if data.HTTPLoadBalancer.HTTPLoadBalancer != nil {
			http_loadbalancerNestedMap := make(map[string]interface{})
			if !data.HTTPLoadBalancer.HTTPLoadBalancer.Name.IsNull() && !data.HTTPLoadBalancer.HTTPLoadBalancer.Name.IsUnknown() {
				http_loadbalancerNestedMap["name"] = data.HTTPLoadBalancer.HTTPLoadBalancer.Name.ValueString()
			}
			if !data.HTTPLoadBalancer.HTTPLoadBalancer.Namespace.IsNull() && !data.HTTPLoadBalancer.HTTPLoadBalancer.Namespace.IsUnknown() {
				http_loadbalancerNestedMap["namespace"] = data.HTTPLoadBalancer.HTTPLoadBalancer.Namespace.ValueString()
			}
			if !data.HTTPLoadBalancer.HTTPLoadBalancer.Tenant.IsNull() && !data.HTTPLoadBalancer.HTTPLoadBalancer.Tenant.IsUnknown() {
				http_loadbalancerNestedMap["tenant"] = data.HTTPLoadBalancer.HTTPLoadBalancer.Tenant.ValueString()
			}
			http_loadbalancerMap["http_loadbalancer"] = http_loadbalancerNestedMap
		}
		createReq.Spec["http_loadbalancer"] = http_loadbalancerMap
	}

	apiResource, err := r.client.CreateAppAPIGroup(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create AppAPIGroup: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["bigip_virtual_server"].(map[string]interface{}); ok && isImport && data.BigIPVirtualServer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.BigIPVirtualServer = &AppAPIGroupBigIPVirtualServerModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["cdn_loadbalancer"].(map[string]interface{}); ok && isImport && data.CDNLoadBalancer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.CDNLoadBalancer = &AppAPIGroupCDNLoadBalancerModel{}
	}
	// Normal Read: preserve existing state value
	if listData, ok := apiResource.Spec["elements"].([]interface{}); ok && len(listData) > 0 {
		var elementsList []AppAPIGroupElementsModel
		var existingElementsItems []AppAPIGroupElementsModel
		if !data.Elements.IsNull() && !data.Elements.IsUnknown() {
			data.Elements.ElementsAs(ctx, &existingElementsItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx // May be unused if no empty marker blocks in list item
			if itemMap, ok := item.(map[string]interface{}); ok {
				elementsList = append(elementsList, AppAPIGroupElementsModel{
					Methods: func() types.List {
						if v, ok := itemMap["methods"].([]interface{}); ok && len(v) > 0 {
							var items []string
							for _, item := range v {
								if s, ok := item.(string); ok {
									items = append(items, s)
								}
							}
							listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
							return listVal
						}
						return types.ListNull(types.StringType)
					}(),
					PathRegex: func() types.String {
						if v, ok := itemMap["path_regex"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: AppAPIGroupElementsModelAttrTypes}, elementsList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Elements = listVal
		}
	} else {
		// No data from API - set to null list
		data.Elements = types.ListNull(types.ObjectType{AttrTypes: AppAPIGroupElementsModelAttrTypes})
	}
	if _, ok := apiResource.Spec["http_loadbalancer"].(map[string]interface{}); ok && isImport && data.HTTPLoadBalancer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.HTTPLoadBalancer = &AppAPIGroupHTTPLoadBalancerModel{}
	}
	// Normal Read: preserve existing state value

	tflog.Trace(ctx, "created AppAPIGroup resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppAPIGroupResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data AppAPIGroupResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	apiResource, err := r.client.GetAppAPIGroup(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "AppAPIGroup not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read AppAPIGroup: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Unmarshal spec fields from API response to Terraform state
	isImport := false // Always false - no state upgrade tracking
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["bigip_virtual_server"].(map[string]interface{}); ok && isImport && data.BigIPVirtualServer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.BigIPVirtualServer = &AppAPIGroupBigIPVirtualServerModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["cdn_loadbalancer"].(map[string]interface{}); ok && isImport && data.CDNLoadBalancer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.CDNLoadBalancer = &AppAPIGroupCDNLoadBalancerModel{}
	}
	// Normal Read: preserve existing state value
	if listData, ok := apiResource.Spec["elements"].([]interface{}); ok && len(listData) > 0 {
		var elementsList []AppAPIGroupElementsModel
		var existingElementsItems []AppAPIGroupElementsModel
		if !data.Elements.IsNull() && !data.Elements.IsUnknown() {
			data.Elements.ElementsAs(ctx, &existingElementsItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx // May be unused if no empty marker blocks in list item
			if itemMap, ok := item.(map[string]interface{}); ok {
				elementsList = append(elementsList, AppAPIGroupElementsModel{
					Methods: func() types.List {
						if v, ok := itemMap["methods"].([]interface{}); ok && len(v) > 0 {
							var items []string
							for _, item := range v {
								if s, ok := item.(string); ok {
									items = append(items, s)
								}
							}
							listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
							return listVal
						}
						return types.ListNull(types.StringType)
					}(),
					PathRegex: func() types.String {
						if v, ok := itemMap["path_regex"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: AppAPIGroupElementsModelAttrTypes}, elementsList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Elements = listVal
		}
	} else {
		// No data from API - set to null list
		data.Elements = types.ListNull(types.ObjectType{AttrTypes: AppAPIGroupElementsModelAttrTypes})
	}
	if _, ok := apiResource.Spec["http_loadbalancer"].(map[string]interface{}); ok && isImport && data.HTTPLoadBalancer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.HTTPLoadBalancer = &AppAPIGroupHTTPLoadBalancerModel{}
	}
	// Normal Read: preserve existing state value

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppAPIGroupResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data AppAPIGroupResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.AppAPIGroup{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.BigIPVirtualServer != nil {
		bigip_virtual_serverMap := make(map[string]interface{})
		if data.BigIPVirtualServer.BigIPVirtualServer != nil {
			bigip_virtual_serverNestedMap := make(map[string]interface{})
			if !data.BigIPVirtualServer.BigIPVirtualServer.Name.IsNull() && !data.BigIPVirtualServer.BigIPVirtualServer.Name.IsUnknown() {
				bigip_virtual_serverNestedMap["name"] = data.BigIPVirtualServer.BigIPVirtualServer.Name.ValueString()
			}
			if !data.BigIPVirtualServer.BigIPVirtualServer.Namespace.IsNull() && !data.BigIPVirtualServer.BigIPVirtualServer.Namespace.IsUnknown() {
				bigip_virtual_serverNestedMap["namespace"] = data.BigIPVirtualServer.BigIPVirtualServer.Namespace.ValueString()
			}
			if !data.BigIPVirtualServer.BigIPVirtualServer.Tenant.IsNull() && !data.BigIPVirtualServer.BigIPVirtualServer.Tenant.IsUnknown() {
				bigip_virtual_serverNestedMap["tenant"] = data.BigIPVirtualServer.BigIPVirtualServer.Tenant.ValueString()
			}
			bigip_virtual_serverMap["bigip_virtual_server"] = bigip_virtual_serverNestedMap
		}
		apiResource.Spec["bigip_virtual_server"] = bigip_virtual_serverMap
	}
	if data.CDNLoadBalancer != nil {
		cdn_loadbalancerMap := make(map[string]interface{})
		if data.CDNLoadBalancer.CDNLoadBalancer != nil {
			cdn_loadbalancerNestedMap := make(map[string]interface{})
			if !data.CDNLoadBalancer.CDNLoadBalancer.Name.IsNull() && !data.CDNLoadBalancer.CDNLoadBalancer.Name.IsUnknown() {
				cdn_loadbalancerNestedMap["name"] = data.CDNLoadBalancer.CDNLoadBalancer.Name.ValueString()
			}
			if !data.CDNLoadBalancer.CDNLoadBalancer.Namespace.IsNull() && !data.CDNLoadBalancer.CDNLoadBalancer.Namespace.IsUnknown() {
				cdn_loadbalancerNestedMap["namespace"] = data.CDNLoadBalancer.CDNLoadBalancer.Namespace.ValueString()
			}
			if !data.CDNLoadBalancer.CDNLoadBalancer.Tenant.IsNull() && !data.CDNLoadBalancer.CDNLoadBalancer.Tenant.IsUnknown() {
				cdn_loadbalancerNestedMap["tenant"] = data.CDNLoadBalancer.CDNLoadBalancer.Tenant.ValueString()
			}
			cdn_loadbalancerMap["cdn_loadbalancer"] = cdn_loadbalancerNestedMap
		}
		apiResource.Spec["cdn_loadbalancer"] = cdn_loadbalancerMap
	}
	if !data.Elements.IsNull() && !data.Elements.IsUnknown() {
		var elementsItems []AppAPIGroupElementsModel
		diags := data.Elements.ElementsAs(ctx, &elementsItems, false)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() && len(elementsItems) > 0 {
			var elementsList []map[string]interface{}
			for _, item := range elementsItems {
				itemMap := make(map[string]interface{})
				if !item.PathRegex.IsNull() && !item.PathRegex.IsUnknown() {
					itemMap["path_regex"] = item.PathRegex.ValueString()
				}
				elementsList = append(elementsList, itemMap)
			}
			apiResource.Spec["elements"] = elementsList
		}
	}
	if data.HTTPLoadBalancer != nil {
		http_loadbalancerMap := make(map[string]interface{})
		if data.HTTPLoadBalancer.HTTPLoadBalancer != nil {
			http_loadbalancerNestedMap := make(map[string]interface{})
			if !data.HTTPLoadBalancer.HTTPLoadBalancer.Name.IsNull() && !data.HTTPLoadBalancer.HTTPLoadBalancer.Name.IsUnknown() {
				http_loadbalancerNestedMap["name"] = data.HTTPLoadBalancer.HTTPLoadBalancer.Name.ValueString()
			}
			if !data.HTTPLoadBalancer.HTTPLoadBalancer.Namespace.IsNull() && !data.HTTPLoadBalancer.HTTPLoadBalancer.Namespace.IsUnknown() {
				http_loadbalancerNestedMap["namespace"] = data.HTTPLoadBalancer.HTTPLoadBalancer.Namespace.ValueString()
			}
			if !data.HTTPLoadBalancer.HTTPLoadBalancer.Tenant.IsNull() && !data.HTTPLoadBalancer.HTTPLoadBalancer.Tenant.IsUnknown() {
				http_loadbalancerNestedMap["tenant"] = data.HTTPLoadBalancer.HTTPLoadBalancer.Tenant.ValueString()
			}
			http_loadbalancerMap["http_loadbalancer"] = http_loadbalancerNestedMap
		}
		apiResource.Spec["http_loadbalancer"] = http_loadbalancerMap
	}

	_, err := r.client.UpdateAppAPIGroup(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update AppAPIGroup: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetAppAPIGroup(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read AppAPIGroup after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["bigip_virtual_server"].(map[string]interface{}); ok && isImport && data.BigIPVirtualServer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.BigIPVirtualServer = &AppAPIGroupBigIPVirtualServerModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["cdn_loadbalancer"].(map[string]interface{}); ok && isImport && data.CDNLoadBalancer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.CDNLoadBalancer = &AppAPIGroupCDNLoadBalancerModel{}
	}
	// Normal Read: preserve existing state value
	if listData, ok := apiResource.Spec["elements"].([]interface{}); ok && len(listData) > 0 {
		var elementsList []AppAPIGroupElementsModel
		var existingElementsItems []AppAPIGroupElementsModel
		if !data.Elements.IsNull() && !data.Elements.IsUnknown() {
			data.Elements.ElementsAs(ctx, &existingElementsItems, false)
		}
		for listIdx, item := range listData {
			_ = listIdx // May be unused if no empty marker blocks in list item
			if itemMap, ok := item.(map[string]interface{}); ok {
				elementsList = append(elementsList, AppAPIGroupElementsModel{
					Methods: func() types.List {
						if v, ok := itemMap["methods"].([]interface{}); ok && len(v) > 0 {
							var items []string
							for _, item := range v {
								if s, ok := item.(string); ok {
									items = append(items, s)
								}
							}
							listVal, _ := types.ListValueFrom(ctx, types.StringType, items)
							return listVal
						}
						return types.ListNull(types.StringType)
					}(),
					PathRegex: func() types.String {
						if v, ok := itemMap["path_regex"].(string); ok && v != "" {
							return types.StringValue(v)
						}
						return types.StringNull()
					}(),
				})
			}
		}
		listVal, diags := types.ListValueFrom(ctx, types.ObjectType{AttrTypes: AppAPIGroupElementsModelAttrTypes}, elementsList)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Elements = listVal
		}
	} else {
		// No data from API - set to null list
		data.Elements = types.ListNull(types.ObjectType{AttrTypes: AppAPIGroupElementsModelAttrTypes})
	}
	if _, ok := apiResource.Spec["http_loadbalancer"].(map[string]interface{}); ok && isImport && data.HTTPLoadBalancer == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.HTTPLoadBalancer = &AppAPIGroupHTTPLoadBalancerModel{}
	}
	// Normal Read: preserve existing state value

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *AppAPIGroupResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data AppAPIGroupResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()
	err := r.client.DeleteAppAPIGroup(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "AppAPIGroup already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "AppAPIGroup delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete AppAPIGroup: %s", err))
		return
	}
}

func (r *AppAPIGroupResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: namespace/name
	parts := strings.Split(req.ID, "/")
	if len(parts) != 2 || parts[0] == "" || parts[1] == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			fmt.Sprintf("Expected import ID format: namespace/name, got: %s", req.ID),
		)
		return
	}
	namespace := parts[0]
	name := parts[1]

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), namespace)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)
}
