// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc/terraform-provider-f5xc/internal/client"
	"github.com/f5xc/terraform-provider-f5xc/internal/privatestate"
	inttimeouts "github.com/f5xc/terraform-provider-f5xc/internal/timeouts"
	"github.com/f5xc/terraform-provider-f5xc/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &CloudConnectResource{}
	_ resource.ResourceWithConfigure      = &CloudConnectResource{}
	_ resource.ResourceWithImportState    = &CloudConnectResource{}
	_ resource.ResourceWithModifyPlan     = &CloudConnectResource{}
	_ resource.ResourceWithUpgradeState   = &CloudConnectResource{}
	_ resource.ResourceWithValidateConfig = &CloudConnectResource{}
)

// cloud_connectSchemaVersion is the schema version for state upgrades
const cloud_connectSchemaVersion int64 = 1

func NewCloudConnectResource() resource.Resource {
	return &CloudConnectResource{}
}

type CloudConnectResource struct {
	client *client.Client
}

// CloudConnectEmptyModel represents empty nested blocks
type CloudConnectEmptyModel struct {
}

// CloudConnectAWSTGWSiteModel represents aws_tgw_site block
type CloudConnectAWSTGWSiteModel struct {
	Cred           *CloudConnectAWSTGWSiteCredModel           `tfsdk:"cred"`
	Site           *CloudConnectAWSTGWSiteSiteModel           `tfsdk:"site"`
	VPCAttachments *CloudConnectAWSTGWSiteVPCAttachmentsModel `tfsdk:"vpc_attachments"`
}

// CloudConnectAWSTGWSiteModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteModel
var CloudConnectAWSTGWSiteModelAttrTypes = map[string]attr.Type{
	"cred":            types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteCredModelAttrTypes},
	"site":            types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteSiteModelAttrTypes},
	"vpc_attachments": types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteVPCAttachmentsModelAttrTypes},
}

// CloudConnectAWSTGWSiteCredModel represents cred block
type CloudConnectAWSTGWSiteCredModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// CloudConnectAWSTGWSiteCredModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteCredModel
var CloudConnectAWSTGWSiteCredModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

// CloudConnectAWSTGWSiteSiteModel represents site block
type CloudConnectAWSTGWSiteSiteModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// CloudConnectAWSTGWSiteSiteModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteSiteModel
var CloudConnectAWSTGWSiteSiteModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

// CloudConnectAWSTGWSiteVPCAttachmentsModel represents vpc_attachments block
type CloudConnectAWSTGWSiteVPCAttachmentsModel struct {
	VPCList []CloudConnectAWSTGWSiteVPCAttachmentsVPCListModel `tfsdk:"vpc_list"`
}

// CloudConnectAWSTGWSiteVPCAttachmentsModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteVPCAttachmentsModel
var CloudConnectAWSTGWSiteVPCAttachmentsModelAttrTypes = map[string]attr.Type{
	"vpc_list": types.ListType{ElemType: types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteVPCAttachmentsVPCListModelAttrTypes}},
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListModel represents vpc_list block
type CloudConnectAWSTGWSiteVPCAttachmentsVPCListModel struct {
	VPCID         types.String                                                   `tfsdk:"vpc_id"`
	CustomRouting *CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingModel `tfsdk:"custom_routing"`
	DefaultRoute  *CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteModel  `tfsdk:"default_route"`
	Labels        *CloudConnectEmptyModel                                        `tfsdk:"labels"`
	ManualRouting *CloudConnectEmptyModel                                        `tfsdk:"manual_routing"`
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteVPCAttachmentsVPCListModel
var CloudConnectAWSTGWSiteVPCAttachmentsVPCListModelAttrTypes = map[string]attr.Type{
	"vpc_id":         types.StringType,
	"custom_routing": types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingModelAttrTypes},
	"default_route":  types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteModelAttrTypes},
	"labels":         types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"manual_routing": types.ObjectType{AttrTypes: map[string]attr.Type{}},
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingModel represents custom_routing block
type CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingModel struct {
	RouteTables []CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingRouteTablesModel `tfsdk:"route_tables"`
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingModel
var CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingModelAttrTypes = map[string]attr.Type{
	"route_tables": types.ListType{ElemType: types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingRouteTablesModelAttrTypes}},
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingRouteTablesModel represents route_tables block
type CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingRouteTablesModel struct {
	RouteTableID types.String `tfsdk:"route_table_id"`
	StaticRoutes types.List   `tfsdk:"static_routes"`
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingRouteTablesModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingRouteTablesModel
var CloudConnectAWSTGWSiteVPCAttachmentsVPCListCustomRoutingRouteTablesModelAttrTypes = map[string]attr.Type{
	"route_table_id": types.StringType,
	"static_routes":  types.ListType{ElemType: types.StringType},
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteModel represents default_route block
type CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteModel struct {
	AllRouteTables       *CloudConnectEmptyModel                                                           `tfsdk:"all_route_tables"`
	SelectiveRouteTables *CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteSelectiveRouteTablesModel `tfsdk:"selective_route_tables"`
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteModel
var CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteModelAttrTypes = map[string]attr.Type{
	"all_route_tables":       types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"selective_route_tables": types.ObjectType{AttrTypes: CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteSelectiveRouteTablesModelAttrTypes},
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteSelectiveRouteTablesModel represents selective_route_tables block
type CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteSelectiveRouteTablesModel struct {
	RouteTableID types.List `tfsdk:"route_table_id"`
}

// CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteSelectiveRouteTablesModelAttrTypes defines the attribute types for CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteSelectiveRouteTablesModel
var CloudConnectAWSTGWSiteVPCAttachmentsVPCListDefaultRouteSelectiveRouteTablesModelAttrTypes = map[string]attr.Type{
	"route_table_id": types.ListType{ElemType: types.StringType},
}

// CloudConnectAzureVNETSiteModel represents azure_vnet_site block
type CloudConnectAzureVNETSiteModel struct {
	Site            *CloudConnectAzureVNETSiteSiteModel            `tfsdk:"site"`
	VNETAttachments *CloudConnectAzureVNETSiteVNETAttachmentsModel `tfsdk:"vnet_attachments"`
}

// CloudConnectAzureVNETSiteModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteModel
var CloudConnectAzureVNETSiteModelAttrTypes = map[string]attr.Type{
	"site":             types.ObjectType{AttrTypes: CloudConnectAzureVNETSiteSiteModelAttrTypes},
	"vnet_attachments": types.ObjectType{AttrTypes: CloudConnectAzureVNETSiteVNETAttachmentsModelAttrTypes},
}

// CloudConnectAzureVNETSiteSiteModel represents site block
type CloudConnectAzureVNETSiteSiteModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// CloudConnectAzureVNETSiteSiteModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteSiteModel
var CloudConnectAzureVNETSiteSiteModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

// CloudConnectAzureVNETSiteVNETAttachmentsModel represents vnet_attachments block
type CloudConnectAzureVNETSiteVNETAttachmentsModel struct {
	VNETList []CloudConnectAzureVNETSiteVNETAttachmentsVNETListModel `tfsdk:"vnet_list"`
}

// CloudConnectAzureVNETSiteVNETAttachmentsModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteVNETAttachmentsModel
var CloudConnectAzureVNETSiteVNETAttachmentsModelAttrTypes = map[string]attr.Type{
	"vnet_list": types.ListType{ElemType: types.ObjectType{AttrTypes: CloudConnectAzureVNETSiteVNETAttachmentsVNETListModelAttrTypes}},
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListModel represents vnet_list block
type CloudConnectAzureVNETSiteVNETAttachmentsVNETListModel struct {
	SubscriptionID types.String                                                        `tfsdk:"subscription_id"`
	VNETID         types.String                                                        `tfsdk:"vnet_id"`
	CustomRouting  *CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingModel `tfsdk:"custom_routing"`
	DefaultRoute   *CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteModel  `tfsdk:"default_route"`
	Labels         *CloudConnectEmptyModel                                             `tfsdk:"labels"`
	ManualRouting  *CloudConnectEmptyModel                                             `tfsdk:"manual_routing"`
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteVNETAttachmentsVNETListModel
var CloudConnectAzureVNETSiteVNETAttachmentsVNETListModelAttrTypes = map[string]attr.Type{
	"subscription_id": types.StringType,
	"vnet_id":         types.StringType,
	"custom_routing":  types.ObjectType{AttrTypes: CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingModelAttrTypes},
	"default_route":   types.ObjectType{AttrTypes: CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteModelAttrTypes},
	"labels":          types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"manual_routing":  types.ObjectType{AttrTypes: map[string]attr.Type{}},
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingModel represents custom_routing block
type CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingModel struct {
	RouteTables []CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingRouteTablesModel `tfsdk:"route_tables"`
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingModel
var CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingModelAttrTypes = map[string]attr.Type{
	"route_tables": types.ListType{ElemType: types.ObjectType{AttrTypes: CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingRouteTablesModelAttrTypes}},
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingRouteTablesModel represents route_tables block
type CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingRouteTablesModel struct {
	RouteTableID types.String `tfsdk:"route_table_id"`
	StaticRoutes types.List   `tfsdk:"static_routes"`
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingRouteTablesModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingRouteTablesModel
var CloudConnectAzureVNETSiteVNETAttachmentsVNETListCustomRoutingRouteTablesModelAttrTypes = map[string]attr.Type{
	"route_table_id": types.StringType,
	"static_routes":  types.ListType{ElemType: types.StringType},
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteModel represents default_route block
type CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteModel struct {
	AllRouteTables       *CloudConnectEmptyModel                                                                `tfsdk:"all_route_tables"`
	SelectiveRouteTables *CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteSelectiveRouteTablesModel `tfsdk:"selective_route_tables"`
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteModel
var CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteModelAttrTypes = map[string]attr.Type{
	"all_route_tables":       types.ObjectType{AttrTypes: map[string]attr.Type{}},
	"selective_route_tables": types.ObjectType{AttrTypes: CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteSelectiveRouteTablesModelAttrTypes},
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteSelectiveRouteTablesModel represents selective_route_tables block
type CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteSelectiveRouteTablesModel struct {
	RouteTableID types.List `tfsdk:"route_table_id"`
}

// CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteSelectiveRouteTablesModelAttrTypes defines the attribute types for CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteSelectiveRouteTablesModel
var CloudConnectAzureVNETSiteVNETAttachmentsVNETListDefaultRouteSelectiveRouteTablesModelAttrTypes = map[string]attr.Type{
	"route_table_id": types.ListType{ElemType: types.StringType},
}

// CloudConnectSegmentModel represents segment block
type CloudConnectSegmentModel struct {
	Name      types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Tenant    types.String `tfsdk:"tenant"`
}

// CloudConnectSegmentModelAttrTypes defines the attribute types for CloudConnectSegmentModel
var CloudConnectSegmentModelAttrTypes = map[string]attr.Type{
	"name":      types.StringType,
	"namespace": types.StringType,
	"tenant":    types.StringType,
}

type CloudConnectResourceModel struct {
	Name          types.String                    `tfsdk:"name"`
	Namespace     types.String                    `tfsdk:"namespace"`
	Annotations   types.Map                       `tfsdk:"annotations"`
	Description   types.String                    `tfsdk:"description"`
	Disable       types.Bool                      `tfsdk:"disable"`
	Labels        types.Map                       `tfsdk:"labels"`
	ID            types.String                    `tfsdk:"id"`
	Timeouts      timeouts.Value                  `tfsdk:"timeouts"`
	AWSTGWSite    *CloudConnectAWSTGWSiteModel    `tfsdk:"aws_tgw_site"`
	AzureVNETSite *CloudConnectAzureVNETSiteModel `tfsdk:"azure_vnet_site"`
	Segment       *CloudConnectSegmentModel       `tfsdk:"segment"`
}

func (r *CloudConnectResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_cloud_connect"
}

func (r *CloudConnectResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Version:             cloud_connectSchemaVersion,
		MarkdownDescription: "Manages a Cloud Connect resource in F5 Distributed Cloud for establishing connectivity to cloud provider networks.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the Cloud Connect. Must be unique within the namespace.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the Cloud Connect will be created.",
				Required:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations is an unstructured key value map stored with a resource that may be set by external tools to store and retrieve arbitrary metadata.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Human readable description for the object.",
				Optional:            true,
			},
			"disable": schema.BoolAttribute{
				MarkdownDescription: "A value of true will administratively disable the object.",
				Optional:            true,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels is a user defined key value map that can be attached to resources for organization and filtering.",
				Optional:            true,
				ElementType:         types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed:            true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"aws_tgw_site": schema.SingleNestedBlock{
				MarkdownDescription: "[OneOf: aws_tgw_site, azure_vnet_site] AWS TGW Site Type. Cloud Connect AWS TGW Site Type.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"cred": schema.SingleNestedBlock{
						MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "Name. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
								Optional:            true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "Namespace. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
								Optional:            true,
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "Tenant. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"site": schema.SingleNestedBlock{
						MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "Name. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
								Optional:            true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "Namespace. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
								Optional:            true,
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "Tenant. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"vpc_attachments": schema.SingleNestedBlock{
						MarkdownDescription: "VPC Attachments.",
						Attributes:          map[string]schema.Attribute{},
						Blocks: map[string]schema.Block{
							"vpc_list": schema.ListNestedBlock{
								MarkdownDescription: "VPC List. Collection of items or values",
								NestedObject: schema.NestedBlockObject{
									Attributes: map[string]schema.Attribute{
										"vpc_id": schema.StringAttribute{
											MarkdownDescription: "VPC ID. Enter the VPC ID of the VPC to be attached .",
											Optional:            true,
										},
									},
									Blocks: map[string]schema.Block{
										"custom_routing": schema.SingleNestedBlock{
											MarkdownDescription: "AWS Route Table List. AWS Route Table List.",
											Attributes:          map[string]schema.Attribute{},
											Blocks: map[string]schema.Block{
												"route_tables": schema.ListNestedBlock{
													MarkdownDescription: "List of route tables. Route Tables .",
													NestedObject: schema.NestedBlockObject{
														Attributes: map[string]schema.Attribute{
															"route_table_id": schema.StringAttribute{
																MarkdownDescription: "Route table ID. Route table ID.",
																Optional:            true,
															},
															"static_routes": schema.ListAttribute{
																MarkdownDescription: "Static Routes. List of Static Routes .",
																Optional:            true,
																ElementType:         types.StringType,
															},
														},
													},
												},
											},
										},
										"default_route": schema.SingleNestedBlock{
											MarkdownDescription: "Override Default Route Choice. Select Override Default Route Choice.",
											Attributes:          map[string]schema.Attribute{},
											Blocks: map[string]schema.Block{
												"all_route_tables": schema.SingleNestedBlock{
													MarkdownDescription: "Enable this option",
												},
												"selective_route_tables": schema.SingleNestedBlock{
													MarkdownDescription: "AWS Route Table. AWS Route Table.",
													Attributes: map[string]schema.Attribute{
														"route_table_id": schema.ListAttribute{
															MarkdownDescription: "Route table ID. Route table ID.",
															Optional:            true,
															ElementType:         types.StringType,
														},
													},
												},
											},
										},
										"labels": schema.SingleNestedBlock{
											MarkdownDescription: "Labels. Add labels for the VPC attachment. These labels can then be used in policies such as enhanced firewall.",
										},
										"manual_routing": schema.SingleNestedBlock{
											MarkdownDescription: "Enable this option",
										},
									},
								},
							},
						},
					},
				},
			},
			"azure_vnet_site": schema.SingleNestedBlock{
				MarkdownDescription: "Azure VNet Site Type. Cloud Connect Azure VNet Site Type.",
				Attributes:          map[string]schema.Attribute{},
				Blocks: map[string]schema.Block{
					"site": schema.SingleNestedBlock{
						MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
						Attributes: map[string]schema.Attribute{
							"name": schema.StringAttribute{
								MarkdownDescription: "Name. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
								Optional:            true,
							},
							"namespace": schema.StringAttribute{
								MarkdownDescription: "Namespace. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
								Optional:            true,
							},
							"tenant": schema.StringAttribute{
								MarkdownDescription: "Tenant. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
								Optional:            true,
								Computed:            true,
								PlanModifiers: []planmodifier.String{
									stringplanmodifier.UseStateForUnknown(),
								},
							},
						},
					},
					"vnet_attachments": schema.SingleNestedBlock{
						MarkdownDescription: "VNet Attachments.",
						Attributes:          map[string]schema.Attribute{},
						Blocks: map[string]schema.Block{
							"vnet_list": schema.ListNestedBlock{
								MarkdownDescription: "VNet List. Collection of items or values",
								NestedObject: schema.NestedBlockObject{
									Attributes: map[string]schema.Attribute{
										"subscription_id": schema.StringAttribute{
											MarkdownDescription: "Subscription ID. Enter the Subscription ID of the VNet to be attached .",
											Optional:            true,
										},
										"vnet_id": schema.StringAttribute{
											MarkdownDescription: "VNet ID. Enter the VNet ID of the VNet to be attached in format /<resource-group-name>/<VNet-name> .",
											Optional:            true,
										},
									},
									Blocks: map[string]schema.Block{
										"custom_routing": schema.SingleNestedBlock{
											MarkdownDescription: "List Azure Route Table with Static Route. List Azure Route Table with Static Route.",
											Attributes:          map[string]schema.Attribute{},
											Blocks: map[string]schema.Block{
												"route_tables": schema.ListNestedBlock{
													MarkdownDescription: "List of route tables with static routes. Route Tables with static routes .",
													NestedObject: schema.NestedBlockObject{
														Attributes: map[string]schema.Attribute{
															"route_table_id": schema.StringAttribute{
																MarkdownDescription: "Route table ID. Route table ID in the format /<resource-group-name>/<route-table-name>",
																Optional:            true,
															},
															"static_routes": schema.ListAttribute{
																MarkdownDescription: "Static Routes. List of Static Routes .",
																Optional:            true,
																ElementType:         types.StringType,
															},
														},
													},
												},
											},
										},
										"default_route": schema.SingleNestedBlock{
											MarkdownDescription: "Override Default Route Choice. Select Override Default Route Choice.",
											Attributes:          map[string]schema.Attribute{},
											Blocks: map[string]schema.Block{
												"all_route_tables": schema.SingleNestedBlock{
													MarkdownDescription: "Enable this option",
												},
												"selective_route_tables": schema.SingleNestedBlock{
													MarkdownDescription: "Azure Route Table. Azure Route Table.",
													Attributes: map[string]schema.Attribute{
														"route_table_id": schema.ListAttribute{
															MarkdownDescription: "Route table ID. Route table ID in the format /<resource-group-name>/<route-table-name>",
															Optional:            true,
															ElementType:         types.StringType,
														},
													},
												},
											},
										},
										"labels": schema.SingleNestedBlock{
											MarkdownDescription: "Labels. Add labels for the VNet attachments. These labels can then be used in policies such as enhanced firewall policies.",
										},
										"manual_routing": schema.SingleNestedBlock{
											MarkdownDescription: "Enable this option",
										},
									},
								},
							},
						},
					},
				},
			},
			"segment": schema.SingleNestedBlock{
				MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name.",
				Attributes: map[string]schema.Attribute{
					"name": schema.StringAttribute{
						MarkdownDescription: "Name. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. Route's) name.",
						Optional:            true,
					},
					"namespace": schema.StringAttribute{
						MarkdownDescription: "Namespace. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. Route's) namespace.",
						Optional:            true,
					},
					"tenant": schema.StringAttribute{
						MarkdownDescription: "Tenant. When a configuration object(e.g. Virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. Route's) tenant.",
						Optional:            true,
						Computed:            true,
						PlanModifiers: []planmodifier.String{
							stringplanmodifier.UseStateForUnknown(),
						},
					},
				},
			},
		},
	}
}

func (r *CloudConnectResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *CloudConnectResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data CloudConnectResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *CloudConnectResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the cloud_connect from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan CloudConnectResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

// UpgradeState implements resource.ResourceWithUpgradeState
func (r *CloudConnectResource) UpgradeState(ctx context.Context) map[int64]resource.StateUpgrader {
	return map[int64]resource.StateUpgrader{
		0: {
			PriorSchema: &schema.Schema{
				Attributes: map[string]schema.Attribute{
					"name":        schema.StringAttribute{Required: true},
					"namespace":   schema.StringAttribute{Required: true},
					"annotations": schema.MapAttribute{Optional: true, ElementType: types.StringType},
					"labels":      schema.MapAttribute{Optional: true, ElementType: types.StringType},
					"id":          schema.StringAttribute{Computed: true},
				},
			},
			StateUpgrader: func(ctx context.Context, req resource.UpgradeStateRequest, resp *resource.UpgradeStateResponse) {
				var priorState struct {
					Name        types.String `tfsdk:"name"`
					Namespace   types.String `tfsdk:"namespace"`
					Annotations types.Map    `tfsdk:"annotations"`
					Labels      types.Map    `tfsdk:"labels"`
					ID          types.String `tfsdk:"id"`
				}

				resp.Diagnostics.Append(req.State.Get(ctx, &priorState)...)
				if resp.Diagnostics.HasError() {
					return
				}

				upgradedState := CloudConnectResourceModel{
					Name:        priorState.Name,
					Namespace:   priorState.Namespace,
					Annotations: priorState.Annotations,
					Labels:      priorState.Labels,
					ID:          priorState.ID,
					Timeouts:    timeouts.Value{},
				}

				resp.Diagnostics.Append(resp.State.Set(ctx, upgradedState)...)
			},
		},
	}
}

func (r *CloudConnectResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data CloudConnectResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating cloud_connect", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	createReq := &client.CloudConnect{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		createReq.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		createReq.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.AWSTGWSite != nil {
		aws_tgw_siteMap := make(map[string]interface{})
		if data.AWSTGWSite.Cred != nil {
			credNestedMap := make(map[string]interface{})
			if !data.AWSTGWSite.Cred.Name.IsNull() && !data.AWSTGWSite.Cred.Name.IsUnknown() {
				credNestedMap["name"] = data.AWSTGWSite.Cred.Name.ValueString()
			}
			if !data.AWSTGWSite.Cred.Namespace.IsNull() && !data.AWSTGWSite.Cred.Namespace.IsUnknown() {
				credNestedMap["namespace"] = data.AWSTGWSite.Cred.Namespace.ValueString()
			}
			if !data.AWSTGWSite.Cred.Tenant.IsNull() && !data.AWSTGWSite.Cred.Tenant.IsUnknown() {
				credNestedMap["tenant"] = data.AWSTGWSite.Cred.Tenant.ValueString()
			}
			aws_tgw_siteMap["cred"] = credNestedMap
		}
		if data.AWSTGWSite.Site != nil {
			siteNestedMap := make(map[string]interface{})
			if !data.AWSTGWSite.Site.Name.IsNull() && !data.AWSTGWSite.Site.Name.IsUnknown() {
				siteNestedMap["name"] = data.AWSTGWSite.Site.Name.ValueString()
			}
			if !data.AWSTGWSite.Site.Namespace.IsNull() && !data.AWSTGWSite.Site.Namespace.IsUnknown() {
				siteNestedMap["namespace"] = data.AWSTGWSite.Site.Namespace.ValueString()
			}
			if !data.AWSTGWSite.Site.Tenant.IsNull() && !data.AWSTGWSite.Site.Tenant.IsUnknown() {
				siteNestedMap["tenant"] = data.AWSTGWSite.Site.Tenant.ValueString()
			}
			aws_tgw_siteMap["site"] = siteNestedMap
		}
		if data.AWSTGWSite.VPCAttachments != nil {
			vpc_attachmentsNestedMap := make(map[string]interface{})
			aws_tgw_siteMap["vpc_attachments"] = vpc_attachmentsNestedMap
		}
		createReq.Spec["aws_tgw_site"] = aws_tgw_siteMap
	}
	if data.AzureVNETSite != nil {
		azure_vnet_siteMap := make(map[string]interface{})
		if data.AzureVNETSite.Site != nil {
			siteNestedMap := make(map[string]interface{})
			if !data.AzureVNETSite.Site.Name.IsNull() && !data.AzureVNETSite.Site.Name.IsUnknown() {
				siteNestedMap["name"] = data.AzureVNETSite.Site.Name.ValueString()
			}
			if !data.AzureVNETSite.Site.Namespace.IsNull() && !data.AzureVNETSite.Site.Namespace.IsUnknown() {
				siteNestedMap["namespace"] = data.AzureVNETSite.Site.Namespace.ValueString()
			}
			if !data.AzureVNETSite.Site.Tenant.IsNull() && !data.AzureVNETSite.Site.Tenant.IsUnknown() {
				siteNestedMap["tenant"] = data.AzureVNETSite.Site.Tenant.ValueString()
			}
			azure_vnet_siteMap["site"] = siteNestedMap
		}
		if data.AzureVNETSite.VNETAttachments != nil {
			vnet_attachmentsNestedMap := make(map[string]interface{})
			azure_vnet_siteMap["vnet_attachments"] = vnet_attachmentsNestedMap
		}
		createReq.Spec["azure_vnet_site"] = azure_vnet_siteMap
	}
	if data.Segment != nil {
		segmentMap := make(map[string]interface{})
		if !data.Segment.Name.IsNull() && !data.Segment.Name.IsUnknown() {
			segmentMap["name"] = data.Segment.Name.ValueString()
		}
		if !data.Segment.Namespace.IsNull() && !data.Segment.Namespace.IsUnknown() {
			segmentMap["namespace"] = data.Segment.Namespace.ValueString()
		}
		if !data.Segment.Tenant.IsNull() && !data.Segment.Tenant.IsUnknown() {
			segmentMap["tenant"] = data.Segment.Tenant.ValueString()
		}
		createReq.Spec["segment"] = segmentMap
	}

	apiResource, err := r.client.CreateCloudConnect(ctx, createReq)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create CloudConnect: %s", err))
		return
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	// For resources without namespace in API path, namespace is computed from API response
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Unmarshal spec fields from API response to Terraform state
	// This ensures computed nested fields (like tenant in Object Reference blocks) have known values
	isImport := false // Create is never an import
	_ = isImport      // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["aws_tgw_site"].(map[string]interface{}); ok && isImport && data.AWSTGWSite == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.AWSTGWSite = &CloudConnectAWSTGWSiteModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["azure_vnet_site"].(map[string]interface{}); ok && isImport && data.AzureVNETSite == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.AzureVNETSite = &CloudConnectAzureVNETSiteModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["segment"].(map[string]interface{}); ok && (isImport || data.Segment != nil) {
		data.Segment = &CloudConnectSegmentModel{
			Name: func() types.String {
				if v, ok := blockData["name"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Namespace: func() types.String {
				if v, ok := blockData["namespace"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Tenant: func() types.String {
				if v, ok := blockData["tenant"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}

	psd := privatestate.NewPrivateStateData()
	psd.SetCustom("managed", "true")
	tflog.Debug(ctx, "Create: saving private state with managed marker", map[string]interface{}{
		"name": apiResource.Metadata.Name,
	})
	resp.Diagnostics.Append(psd.SaveToPrivateState(ctx, resp)...)

	tflog.Trace(ctx, "created CloudConnect resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CloudConnectResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data CloudConnectResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	psd, psDiags := privatestate.LoadFromPrivateState(ctx, &req)
	resp.Diagnostics.Append(psDiags...)

	apiResource, err := r.client.GetCloudConnect(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// Check if the resource was deleted outside Terraform
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "CloudConnect not found, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read CloudConnect: %s", err))
		return
	}

	if psd != nil && psd.Metadata.UID != "" && apiResource.Metadata.UID != psd.Metadata.UID {
		resp.Diagnostics.AddWarning(
			"Resource Drift Detected",
			"The cloud_connect may have been recreated outside of Terraform.",
		)
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	// Read description from metadata
	if apiResource.Metadata.Description != "" {
		data.Description = types.StringValue(apiResource.Metadata.Description)
	} else {
		data.Description = types.StringNull()
	}

	// Filter out system-managed labels (ves.io/*) that are injected by the platform
	if len(apiResource.Metadata.Labels) > 0 {
		filteredLabels := filterSystemLabels(apiResource.Metadata.Labels)
		if len(filteredLabels) > 0 {
			labels, diags := types.MapValueFrom(ctx, types.StringType, filteredLabels)
			resp.Diagnostics.Append(diags...)
			if !resp.Diagnostics.HasError() {
				data.Labels = labels
			}
		} else {
			data.Labels = types.MapNull(types.StringType)
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	// Unmarshal spec fields from API response to Terraform state
	// isImport is true when private state has no "managed" marker (Import case - never went through Create)
	isImport := psd == nil || psd.Metadata.Custom == nil || psd.Metadata.Custom["managed"] != "true"
	_ = isImport // May be unused if resource has no blocks needing import detection
	tflog.Debug(ctx, "Read: checking isImport status", map[string]interface{}{
		"isImport":   isImport,
		"psd_is_nil": psd == nil,
		"managed":    psd.Metadata.Custom["managed"],
	})
	if _, ok := apiResource.Spec["aws_tgw_site"].(map[string]interface{}); ok && isImport && data.AWSTGWSite == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.AWSTGWSite = &CloudConnectAWSTGWSiteModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["azure_vnet_site"].(map[string]interface{}); ok && isImport && data.AzureVNETSite == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.AzureVNETSite = &CloudConnectAzureVNETSiteModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["segment"].(map[string]interface{}); ok && (isImport || data.Segment != nil) {
		data.Segment = &CloudConnectSegmentModel{
			Name: func() types.String {
				if v, ok := blockData["name"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Namespace: func() types.String {
				if v, ok := blockData["namespace"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Tenant: func() types.String {
				if v, ok := blockData["tenant"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}

	// Preserve or set the managed marker for future Read operations
	newPsd := privatestate.NewPrivateStateData()
	newPsd.SetUID(apiResource.Metadata.UID)
	if !isImport {
		// Preserve the managed marker if we already had it
		newPsd.SetCustom("managed", "true")
	}
	resp.Diagnostics.Append(newPsd.SaveToPrivateState(ctx, resp)...)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CloudConnectResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data CloudConnectResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.CloudConnect{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: make(map[string]interface{}),
	}

	if !data.Description.IsNull() {
		apiResource.Metadata.Description = data.Description.ValueString()
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	// Marshal spec fields from Terraform state to API struct
	if data.AWSTGWSite != nil {
		aws_tgw_siteMap := make(map[string]interface{})
		if data.AWSTGWSite.Cred != nil {
			credNestedMap := make(map[string]interface{})
			if !data.AWSTGWSite.Cred.Name.IsNull() && !data.AWSTGWSite.Cred.Name.IsUnknown() {
				credNestedMap["name"] = data.AWSTGWSite.Cred.Name.ValueString()
			}
			if !data.AWSTGWSite.Cred.Namespace.IsNull() && !data.AWSTGWSite.Cred.Namespace.IsUnknown() {
				credNestedMap["namespace"] = data.AWSTGWSite.Cred.Namespace.ValueString()
			}
			if !data.AWSTGWSite.Cred.Tenant.IsNull() && !data.AWSTGWSite.Cred.Tenant.IsUnknown() {
				credNestedMap["tenant"] = data.AWSTGWSite.Cred.Tenant.ValueString()
			}
			aws_tgw_siteMap["cred"] = credNestedMap
		}
		if data.AWSTGWSite.Site != nil {
			siteNestedMap := make(map[string]interface{})
			if !data.AWSTGWSite.Site.Name.IsNull() && !data.AWSTGWSite.Site.Name.IsUnknown() {
				siteNestedMap["name"] = data.AWSTGWSite.Site.Name.ValueString()
			}
			if !data.AWSTGWSite.Site.Namespace.IsNull() && !data.AWSTGWSite.Site.Namespace.IsUnknown() {
				siteNestedMap["namespace"] = data.AWSTGWSite.Site.Namespace.ValueString()
			}
			if !data.AWSTGWSite.Site.Tenant.IsNull() && !data.AWSTGWSite.Site.Tenant.IsUnknown() {
				siteNestedMap["tenant"] = data.AWSTGWSite.Site.Tenant.ValueString()
			}
			aws_tgw_siteMap["site"] = siteNestedMap
		}
		if data.AWSTGWSite.VPCAttachments != nil {
			vpc_attachmentsNestedMap := make(map[string]interface{})
			aws_tgw_siteMap["vpc_attachments"] = vpc_attachmentsNestedMap
		}
		apiResource.Spec["aws_tgw_site"] = aws_tgw_siteMap
	}
	if data.AzureVNETSite != nil {
		azure_vnet_siteMap := make(map[string]interface{})
		if data.AzureVNETSite.Site != nil {
			siteNestedMap := make(map[string]interface{})
			if !data.AzureVNETSite.Site.Name.IsNull() && !data.AzureVNETSite.Site.Name.IsUnknown() {
				siteNestedMap["name"] = data.AzureVNETSite.Site.Name.ValueString()
			}
			if !data.AzureVNETSite.Site.Namespace.IsNull() && !data.AzureVNETSite.Site.Namespace.IsUnknown() {
				siteNestedMap["namespace"] = data.AzureVNETSite.Site.Namespace.ValueString()
			}
			if !data.AzureVNETSite.Site.Tenant.IsNull() && !data.AzureVNETSite.Site.Tenant.IsUnknown() {
				siteNestedMap["tenant"] = data.AzureVNETSite.Site.Tenant.ValueString()
			}
			azure_vnet_siteMap["site"] = siteNestedMap
		}
		if data.AzureVNETSite.VNETAttachments != nil {
			vnet_attachmentsNestedMap := make(map[string]interface{})
			azure_vnet_siteMap["vnet_attachments"] = vnet_attachmentsNestedMap
		}
		apiResource.Spec["azure_vnet_site"] = azure_vnet_siteMap
	}
	if data.Segment != nil {
		segmentMap := make(map[string]interface{})
		if !data.Segment.Name.IsNull() && !data.Segment.Name.IsUnknown() {
			segmentMap["name"] = data.Segment.Name.ValueString()
		}
		if !data.Segment.Namespace.IsNull() && !data.Segment.Namespace.IsUnknown() {
			segmentMap["namespace"] = data.Segment.Namespace.ValueString()
		}
		if !data.Segment.Tenant.IsNull() && !data.Segment.Tenant.IsUnknown() {
			segmentMap["tenant"] = data.Segment.Tenant.ValueString()
		}
		apiResource.Spec["segment"] = segmentMap
	}

	_, err := r.client.UpdateCloudConnect(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update CloudConnect: %s", err))
		return
	}

	// Use plan data for ID since API response may not include metadata.name
	data.ID = types.StringValue(data.Name.ValueString())

	// Fetch the resource to get complete state including computed fields
	// PUT responses may not include all computed nested fields (like tenant in Object Reference blocks)
	fetched, fetchErr := r.client.GetCloudConnect(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if fetchErr != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read CloudConnect after update: %s", fetchErr))
		return
	}

	// Set computed fields from API response

	// Unmarshal spec fields from fetched resource to Terraform state
	apiResource = fetched // Use GET response which includes all computed fields
	isImport := false     // Update is never an import
	_ = isImport          // May be unused if resource has no blocks needing import detection
	if _, ok := apiResource.Spec["aws_tgw_site"].(map[string]interface{}); ok && isImport && data.AWSTGWSite == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.AWSTGWSite = &CloudConnectAWSTGWSiteModel{}
	}
	// Normal Read: preserve existing state value
	if _, ok := apiResource.Spec["azure_vnet_site"].(map[string]interface{}); ok && isImport && data.AzureVNETSite == nil {
		// Import case: populate from API since state is nil and psd is empty
		data.AzureVNETSite = &CloudConnectAzureVNETSiteModel{}
	}
	// Normal Read: preserve existing state value
	if blockData, ok := apiResource.Spec["segment"].(map[string]interface{}); ok && (isImport || data.Segment != nil) {
		data.Segment = &CloudConnectSegmentModel{
			Name: func() types.String {
				if v, ok := blockData["name"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Namespace: func() types.String {
				if v, ok := blockData["namespace"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
			Tenant: func() types.String {
				if v, ok := blockData["tenant"].(string); ok && v != "" {
					return types.StringValue(v)
				}
				return types.StringNull()
			}(),
		}
	}

	psd := privatestate.NewPrivateStateData()
	// Use UID from fetched resource
	uid := fetched.Metadata.UID
	psd.SetUID(uid)
	psd.SetCustom("managed", "true") // Preserve managed marker after Update
	resp.Diagnostics.Append(psd.SaveToPrivateState(ctx, resp)...)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *CloudConnectResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data CloudConnectResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()
	err := r.client.DeleteCloudConnect(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		// If the resource is already gone, consider deletion successful (idempotent delete)
		if strings.Contains(err.Error(), "NOT_FOUND") || strings.Contains(err.Error(), "404") {
			tflog.Warn(ctx, "CloudConnect already deleted, removing from state", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		// If delete is not implemented (501), warn and remove from state
		// Some F5 XC resources don't support deletion via API
		if strings.Contains(err.Error(), "501") {
			tflog.Warn(ctx, "CloudConnect delete not supported by API (501), removing from state only", map[string]interface{}{
				"name":      data.Name.ValueString(),
				"namespace": data.Namespace.ValueString(),
			})
			return
		}
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete CloudConnect: %s", err))
		return
	}
}

func (r *CloudConnectResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	// Import ID format: name (no namespace for this resource type)
	name := req.ID
	if name == "" {
		resp.Diagnostics.AddError(
			"Invalid Import ID",
			"Expected import ID to be the resource name, got empty string",
		)
		return
	}

	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("namespace"), "")...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("name"), name)...)
	resp.Diagnostics.Append(resp.State.SetAttribute(ctx, path.Root("id"), name)...)
}
