// Code generated by generate-all-schemas.go. DO NOT EDIT.
// Source: F5 XC OpenAPI specification

package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-timeouts/resource/timeouts"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-log/tflog"

	"github.com/f5xc/terraform-provider-f5xc/internal/client"
	"github.com/f5xc/terraform-provider-f5xc/internal/privatestate"
	inttimeouts "github.com/f5xc/terraform-provider-f5xc/internal/timeouts"
	"github.com/f5xc/terraform-provider-f5xc/internal/validators"
)

// Ensure provider defined types fully satisfy framework interfaces.
var (
	_ resource.Resource                   = &RouteResource{}
	_ resource.ResourceWithConfigure      = &RouteResource{}
	_ resource.ResourceWithImportState    = &RouteResource{}
	_ resource.ResourceWithModifyPlan     = &RouteResource{}
	_ resource.ResourceWithUpgradeState   = &RouteResource{}
	_ resource.ResourceWithValidateConfig = &RouteResource{}
)

// routeSchemaVersion is the schema version for state upgrades
const routeSchemaVersion int64 = 1

func NewRouteResource() resource.Resource {
	return &RouteResource{}
}

type RouteResource struct {
	client *client.Client
}

type RouteResourceModel struct {
	Name types.String `tfsdk:"name"`
	Namespace types.String `tfsdk:"namespace"`
	Annotations types.Map `tfsdk:"annotations"`
	Labels types.Map `tfsdk:"labels"`
	ID types.String `tfsdk:"id"`
	Timeouts timeouts.Value `tfsdk:"timeouts"`
}

func (r *RouteResource) Metadata(ctx context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_route"
}

func (r *RouteResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		Version:             routeSchemaVersion,
		MarkdownDescription: "Manages a Route resource in F5 Distributed Cloud for defining traffic routing rules for load balancers.",
		Attributes: map[string]schema.Attribute{
			"name": schema.StringAttribute{
				MarkdownDescription: "Name of the Route. Must be unique within the namespace.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NameValidator(),
				},
			},
			"namespace": schema.StringAttribute{
				MarkdownDescription: "Namespace where the Route will be created.",
				Required: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					validators.NamespaceValidator(),
				},
			},
			"annotations": schema.MapAttribute{
				MarkdownDescription: "Annotations to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"labels": schema.MapAttribute{
				MarkdownDescription: "Labels to apply to this resource.",
				Optional: true,
				ElementType: types.StringType,
			},
			"id": schema.StringAttribute{
				MarkdownDescription: "Unique identifier for the resource.",
				Computed: true,
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
		},
		Blocks: map[string]schema.Block{
			"timeouts": timeouts.Block(ctx, timeouts.Opts{
				Create: true,
				Read:   true,
				Update: true,
				Delete: true,
			}),
			"routes": schema.ListNestedBlock{
				MarkdownDescription: "Routes. List of routes to match for incoming request",
				NestedObject: schema.NestedBlockObject{
					Attributes: map[string]schema.Attribute{
						"disable_location_add": schema.BoolAttribute{
							MarkdownDescription: "Disable Location Addition. disables append of x-volterra-location = <re-site-name> at route level, if it is configured at virtual-host level. This configuration is ignored on CE sites.",
							Optional: true,
						},
						"request_cookies_to_remove": schema.ListAttribute{
							MarkdownDescription: "Remove Cookies from Cookie Header. List of keys of Cookies to be removed from the HTTP request being sent towards upstream.",
							Optional: true,
							ElementType: types.StringType,
						},
						"request_headers_to_remove": schema.ListAttribute{
							MarkdownDescription: "Request Headers to Remove. List of keys of Headers to be removed from the HTTP request being sent towards upstream.",
							Optional: true,
							ElementType: types.StringType,
						},
						"response_cookies_to_remove": schema.ListAttribute{
							MarkdownDescription: "Remove Cookies from Set-Cookie Headers. List of name of Cookies to be removed from the HTTP response being sent towards downstream. Entire set-cookie header will be removed",
							Optional: true,
							ElementType: types.StringType,
						},
						"response_headers_to_remove": schema.ListAttribute{
							MarkdownDescription: "Response Headers to Remove. List of keys of Headers to be removed from the HTTP response being sent towards downstream.",
							Optional: true,
							ElementType: types.StringType,
						},
					},
					Blocks: map[string]schema.Block{
						"bot_defense_javascript_injection": schema.SingleNestedBlock{
							MarkdownDescription: "Bot Defense Javascript Injection Configuration for inline deployments. Bot Defense Javascript Injection Configuration for inline bot defense deployments",
							Attributes: map[string]schema.Attribute{
								"javascript_location": schema.StringAttribute{
									MarkdownDescription: "JavaScript Location. All inside networks. Insert JavaScript after <head> tag Insert JavaScript after </title> tag. Insert JavaScript before first <script> tag. Possible values are `AFTER_HEAD`, `AFTER_TITLE_END`, `BEFORE_SCRIPT`. Defaults to `AFTER_HEAD`.",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"javascript_tags": schema.ListNestedBlock{
									MarkdownDescription: "JavaScript Tags. Select Add item to configure your javascript tag. If adding both Bot Adv and Fraud, the Bot Javascript should be added first.",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"javascript_url": schema.StringAttribute{
												MarkdownDescription: "URL. Please enter the full URL (include domain and path), or relative path.",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"tag_attributes": schema.ListNestedBlock{
												MarkdownDescription: "Tag Attributes. Add the tag attributes you want to include in your Javascript tag.",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
										},
									},
								},
							},
						},
						"inherited_bot_defense_javascript_injection": schema.SingleNestedBlock{
							MarkdownDescription: "Empty. This can be used for messages where no values are needed",
						},
						"inherited_waf_exclusion": schema.SingleNestedBlock{
							MarkdownDescription: "Empty. This can be used for messages where no values are needed",
						},
						"match": schema.ListNestedBlock{
							MarkdownDescription: "Match. route match condition",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"http_method": schema.StringAttribute{
										MarkdownDescription: "HTTP Method. Specifies the HTTP method used to access a resource. Any HTTP Method. Possible values are `ANY`, `GET`, `HEAD`, `POST`, `PUT`, `DELETE`, `CONNECT`, `OPTIONS`, `TRACE`, `PATCH`, `COPY`. Defaults to `ANY`.",
										Optional: true,
									},
								},
								Blocks: map[string]schema.Block{
									"headers": schema.ListNestedBlock{
										MarkdownDescription: "Headers. List of (key, value) headers",
										NestedObject: schema.NestedBlockObject{
											Attributes: map[string]schema.Attribute{
												"exact": schema.StringAttribute{
													MarkdownDescription: "Exact. Header value to match exactly",
													Optional: true,
												},
												"invert_match": schema.BoolAttribute{
													MarkdownDescription: "NOT of match. Invert the result of the match to detect missing header or non-matching value",
													Optional: true,
												},
												"name": schema.StringAttribute{
													MarkdownDescription: "Name. Name of the header",
													Optional: true,
												},
												"presence": schema.BoolAttribute{
													MarkdownDescription: "Presence. If true, check for presence of header",
													Optional: true,
												},
												"regex": schema.StringAttribute{
													MarkdownDescription: "Regex. Regex match of the header value in re2 format",
													Optional: true,
												},
											},
										},
									},
									"incoming_port": schema.SingleNestedBlock{
										MarkdownDescription: "Port to Match. Port match of the request can be a range or a specific port",
										Attributes: map[string]schema.Attribute{
											"port": schema.Int64Attribute{
												MarkdownDescription: "Port. Exact Port to match",
												Optional: true,
											},
											"port_ranges": schema.StringAttribute{
												MarkdownDescription: "Port range. Port range to match",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"no_port_match": schema.SingleNestedBlock{
												MarkdownDescription: "Empty. This can be used for messages where no values are needed",
											},
										},
									},
									"path": schema.SingleNestedBlock{
										MarkdownDescription: "Path to Match. Path match of the URI can be either be, Prefix match or exact match or regular expression match",
										Attributes: map[string]schema.Attribute{
											"path": schema.StringAttribute{
												MarkdownDescription: "Exact. Exact path value to match",
												Optional: true,
											},
											"prefix": schema.StringAttribute{
												MarkdownDescription: "Prefix. Path prefix to match (e.g. the value / will match on all paths)",
												Optional: true,
											},
											"regex": schema.StringAttribute{
												MarkdownDescription: "Regex. Regular expression of path match (e.g. the value .* will match on all paths)",
												Optional: true,
											},
										},
									},
									"query_params": schema.ListNestedBlock{
										MarkdownDescription: "Query Parameters. List of (key, value) query parameters",
										NestedObject: schema.NestedBlockObject{
											Attributes: map[string]schema.Attribute{
												"exact": schema.StringAttribute{
													MarkdownDescription: "Exact. Exact match value for the query parameter key",
													Optional: true,
												},
												"key": schema.StringAttribute{
													MarkdownDescription: "Key. Query parameter key In the above example, assignee_username is the key",
													Optional: true,
												},
												"regex": schema.StringAttribute{
													MarkdownDescription: "Regex. Regex match value for the query parameter key",
													Optional: true,
												},
											},
										},
									},
								},
							},
						},
						"request_cookies_to_add": schema.ListNestedBlock{
							MarkdownDescription: "Add Cookies in Cookie Header. Cookies are key-value pairs to be added to HTTP request being routed towards upstream.",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"name": schema.StringAttribute{
										MarkdownDescription: "Name. Name of the cookie in Cookie header.",
										Optional: true,
									},
									"overwrite": schema.BoolAttribute{
										MarkdownDescription: "Overwrite. Should the value be overwritten? If true, the value is overwritten to existing values. Default value is do not overwrite",
										Optional: true,
									},
									"value": schema.StringAttribute{
										MarkdownDescription: "Value. Value of the Cookie header.",
										Optional: true,
									},
								},
								Blocks: map[string]schema.Block{
									"secret_value": schema.SingleNestedBlock{
										MarkdownDescription: "Secret. SecretType is used in an object to indicate a sensitive/confidential field",
										Attributes: map[string]schema.Attribute{
										},
										Blocks: map[string]schema.Block{
											"blindfold_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "Blindfold Secret. BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management",
											},
											"clear_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "In-Clear Secret. ClearSecretInfoType specifies information about the Secret that is not encrypted.",
											},
										},
									},
								},
							},
						},
						"request_headers_to_add": schema.ListNestedBlock{
							MarkdownDescription: "Request Headers to Add. Headers are key-value pairs to be added to HTTP requests being sent towards upstream. Headers specified at this level are applied before headers from the enclosing VirtualHost object level",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"append": schema.BoolAttribute{
										MarkdownDescription: "Append. Should the value be appended? If true, the value is appended to existing values. Default value is do not append",
										Optional: true,
									},
									"name": schema.StringAttribute{
										MarkdownDescription: "Name. Name of the HTTP header.",
										Optional: true,
									},
									"value": schema.StringAttribute{
										MarkdownDescription: "Value. Value of the HTTP header.",
										Optional: true,
									},
								},
								Blocks: map[string]schema.Block{
									"secret_value": schema.SingleNestedBlock{
										MarkdownDescription: "Secret. SecretType is used in an object to indicate a sensitive/confidential field",
										Attributes: map[string]schema.Attribute{
										},
										Blocks: map[string]schema.Block{
											"blindfold_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "Blindfold Secret. BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management",
											},
											"clear_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "In-Clear Secret. ClearSecretInfoType specifies information about the Secret that is not encrypted.",
											},
										},
									},
								},
							},
						},
						"response_cookies_to_add": schema.ListNestedBlock{
							MarkdownDescription: "Add Set-Cookie Headers. Cookies are name-value pairs along with optional attribute parameters to be added to HTTP response being sent towards downstream.",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"add_domain": schema.StringAttribute{
										MarkdownDescription: "Add Domain. Add domain attribute",
										Optional: true,
									},
									"add_expiry": schema.StringAttribute{
										MarkdownDescription: "Add expiry. Add expiry attribute",
										Optional: true,
									},
									"add_path": schema.StringAttribute{
										MarkdownDescription: "Add path. Add path attribute",
										Optional: true,
									},
									"max_age_value": schema.Int64Attribute{
										MarkdownDescription: "Add Max Age. Add max age attribute",
										Optional: true,
									},
									"name": schema.StringAttribute{
										MarkdownDescription: "Name. Name of the cookie in Cookie header.",
										Optional: true,
									},
									"overwrite": schema.BoolAttribute{
										MarkdownDescription: "Overwrite. Should the value be overwritten? If true, the value is overwritten to existing values. Default value is do not overwrite",
										Optional: true,
									},
									"value": schema.StringAttribute{
										MarkdownDescription: "Value. Value of the Cookie header.",
										Optional: true,
									},
								},
								Blocks: map[string]schema.Block{
									"add_httponly": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"add_partitioned": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"add_secure": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_domain": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_expiry": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_httponly": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_max_age": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_partitioned": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_path": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_samesite": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_secure": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"ignore_value": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"samesite_lax": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"samesite_none": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"samesite_strict": schema.SingleNestedBlock{
										MarkdownDescription: "Empty. This can be used for messages where no values are needed",
									},
									"secret_value": schema.SingleNestedBlock{
										MarkdownDescription: "Secret. SecretType is used in an object to indicate a sensitive/confidential field",
										Attributes: map[string]schema.Attribute{
										},
										Blocks: map[string]schema.Block{
											"blindfold_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "Blindfold Secret. BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management",
											},
											"clear_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "In-Clear Secret. ClearSecretInfoType specifies information about the Secret that is not encrypted.",
											},
										},
									},
								},
							},
						},
						"response_headers_to_add": schema.ListNestedBlock{
							MarkdownDescription: "Response Headers to Add. Headers are key-value pairs to be added to HTTP response being sent towards downstream. Headers specified at this level are applied before headers from the enclosing VirtualHost object level",
							NestedObject: schema.NestedBlockObject{
								Attributes: map[string]schema.Attribute{
									"append": schema.BoolAttribute{
										MarkdownDescription: "Append. Should the value be appended? If true, the value is appended to existing values. Default value is do not append",
										Optional: true,
									},
									"name": schema.StringAttribute{
										MarkdownDescription: "Name. Name of the HTTP header.",
										Optional: true,
									},
									"value": schema.StringAttribute{
										MarkdownDescription: "Value. Value of the HTTP header.",
										Optional: true,
									},
								},
								Blocks: map[string]schema.Block{
									"secret_value": schema.SingleNestedBlock{
										MarkdownDescription: "Secret. SecretType is used in an object to indicate a sensitive/confidential field",
										Attributes: map[string]schema.Attribute{
										},
										Blocks: map[string]schema.Block{
											"blindfold_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "Blindfold Secret. BlindfoldSecretInfoType specifies information about the Secret managed by F5XC Secret Management",
											},
											"clear_secret_info": schema.SingleNestedBlock{
												MarkdownDescription: "In-Clear Secret. ClearSecretInfoType specifies information about the Secret that is not encrypted.",
											},
										},
									},
								},
							},
						},
						"route_destination": schema.SingleNestedBlock{
							MarkdownDescription: "Destination List. List of destination to choose if the route is match.",
							Attributes: map[string]schema.Attribute{
								"auto_host_rewrite": schema.BoolAttribute{
									MarkdownDescription: "Automatic Host Rewrite. Indicates that during forwarding, the host header will be swapped with the hostname of the upstream host chosen by the cluster",
									Optional: true,
								},
								"host_rewrite": schema.StringAttribute{
									MarkdownDescription: "Host Rewrite. Indicates that during forwarding, the host header will be swapped with this value",
									Optional: true,
								},
								"prefix_rewrite": schema.StringAttribute{
									MarkdownDescription: "Prefix Rewrite. prefix_rewrite indicates that during forwarding, the matched prefix (or path) should be swapped with its value. When using regex path matching, the entire path (not including the query string) will be swapped with this value. This option allows application URLs to be rooted at a different path from those exposed at the reverse proxy layer. Example : gcSpec: routes: - match: - headers: [] path: prefix : /register/ query_params: [] - headers: [] path: prefix: /register query_params: [] routeDestination: prefixRewrite: '/' destinations: - cluster: - kind: cluster.Object uid: cluster-1 Having above entries in the config, requests to /register will be stripped to /, while requests to /register/public will be stripped to /public",
									Optional: true,
								},
								"priority": schema.StringAttribute{
									MarkdownDescription: "Routing Priority. Priority routing for each request. Different connection pools are used based on the priority selected for the request. Also, circuit-breaker configuration at destination cluster is chosen based on selected priority. Default routing mechanism High-Priority routing mechanism. Possible values are `DEFAULT`, `HIGH`. Defaults to `DEFAULT`.",
									Optional: true,
								},
								"timeout": schema.Int64Attribute{
									MarkdownDescription: "Timeout. Specifies the timeout for the route in milliseconds. This timeout includes all retries. For server side streaming, configure this field with higher value or leave it un-configured for infinite timeout",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"buffer_policy": schema.SingleNestedBlock{
									MarkdownDescription: "Buffer Configuration. Some upstream applications are not capable of handling streamed data. This config enables buffering the entire request before sending to upstream application. We can specify the maximum buffer size and buffer interval with this config. Buffering can be enabled and disabled at VirtualHost and Route levels Route level buffer configuration takes precedence.",
									Attributes: map[string]schema.Attribute{
										"disabled": schema.BoolAttribute{
											MarkdownDescription: "Disable. Disable buffering for a particular route. This is useful when virtual-host has buffering, but we need to disable it on a specific route. The value of this field is ignored for virtual-host",
											Optional: true,
										},
										"max_request_bytes": schema.Int64Attribute{
											MarkdownDescription: "Max Request Bytes. The maximum request size that the filter will buffer before the connection manager will stop buffering and return a RequestEntityTooLarge (413) response.",
											Optional: true,
										},
									},
								},
								"cors_policy": schema.SingleNestedBlock{
									MarkdownDescription: "CORS Policy. Cross-Origin Resource Sharing requests configuration specified at Virtual-host or Route level. Route level configuration takes precedence. An example of an Cross origin HTTP request GET /resources/public-data/ HTTP/1.1 Host: bar.other User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3pre) Gecko/20081130 Minefield/3.1b3pre Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-us,en;q=0.5 Accept-Encoding: gzip,deflate Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7 Connection: keep-alive Referrer: http://foo.example/examples/access-control/simpleXSInvocation.html Origin: http://foo.example HTTP/1.1 200 OK Date: Mon, 01 Dec 2008 00:23:53 GMT Server: Apache/2.0.61 Access-Control-Allow-Origin: * Keep-Alive: timeout=2, max=100 Connection: Keep-Alive Transfer-Encoding: chunked Content-Type: application/xml An example for cross origin HTTP OPTIONS request with Access-Control-Request-* header OPTIONS /resources/post-here/ HTTP/1.1 Host: bar.other User-Agent: Mozilla/5.0 (Macintosh; U; Intel Mac OS X 10.5; en-US; rv:1.9.1b3pre) Gecko/20081130 Minefield/3.1b3pre Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8 Accept-Language: en-us,en;q=0.5 Accept-Encoding: gzip,deflate Accept-Charset: ISO-8859-1,utf-8;q=0.7,*;q=0.7 Connection: keep-alive Origin: http://foo.example Access-Control-Request-Method: POST Access-Control-Request-Headers: X-PINGOTHER, Content-Type HTTP/1.1 204 No Content Date: Mon, 01 Dec 2008 01:15:39 GMT Server: Apache/2.0.61 (Unix) Access-Control-Allow-Origin: http://foo.example Access-Control-Allow-Methods: POST, GET, OPTIONS Access-Control-Allow-Headers: X-PINGOTHER, Content-Type Access-Control-Max-Age: 86400 Vary: Accept-Encoding, Origin Keep-Alive: timeout=2, max=100 Connection: Keep-Alive",
									Attributes: map[string]schema.Attribute{
										"allow_credentials": schema.BoolAttribute{
											MarkdownDescription: "Allow Credentials. Specifies whether the resource allows credentials",
											Optional: true,
										},
										"allow_headers": schema.StringAttribute{
											MarkdownDescription: "Allow Headers. Specifies the content for the access-control-allow-headers header",
											Optional: true,
										},
										"allow_methods": schema.StringAttribute{
											MarkdownDescription: "Allow Methods. Specifies the content for the access-control-allow-methods header",
											Optional: true,
										},
										"allow_origin": schema.ListAttribute{
											MarkdownDescription: "Allow Origin. Specifies the origins that will be allowed to do CORS requests. An origin is allowed if either allow_origin or allow_origin_regex match",
											Optional: true,
											ElementType: types.StringType,
										},
										"allow_origin_regex": schema.ListAttribute{
											MarkdownDescription: "Allow Origin Regex. Specifies regex patterns that match allowed origins. An origin is allowed if either allow_origin or allow_origin_regex match",
											Optional: true,
											ElementType: types.StringType,
										},
										"disabled": schema.BoolAttribute{
											MarkdownDescription: "Disabled. Disable the CorsPolicy for a particular route. This is useful when virtual-host has CorsPolicy, but we need to disable it on a specific route. The value of this field is ignored for virtual-host",
											Optional: true,
										},
										"expose_headers": schema.StringAttribute{
											MarkdownDescription: "Expose Headers. Specifies the content for the access-control-expose-headers header",
											Optional: true,
										},
										"maximum_age": schema.Int64Attribute{
											MarkdownDescription: "Maximum Age. Specifies the content for the access-control-max-age header in seconds. This indicates the maximum number of seconds the results can be cached A value of -1 will disable caching. Maximum permitted value is 86400 seconds (24 hours)",
											Optional: true,
										},
									},
								},
								"csrf_policy": schema.SingleNestedBlock{
									MarkdownDescription: "CSRF Policy. To mitigate CSRF attack , the policy checks where a request is coming from to determine if the request's origin is the same as its detination.The policy relies on two pieces of information used in determining if a request originated from the same host. 1. The origin that caused the user agent to issue the request (source origin). 2. The origin that the request is going to (target origin). When the policy evaluating a request, it ensures both pieces of information are present and compare their values. If the source origin is missing or origins do not match the request is rejected. The exception to this being if the source-origin has been added to they policy as valid. Because CSRF attacks specifically target state-changing requests, the policy only acts on the HTTP requests that have state-changing method (PUT,POST, etc.).",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"all_load_balancer_domains": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"custom_domain_list": schema.SingleNestedBlock{
											MarkdownDescription: "Domain name list. List of domain names used for Host header matching",
										},
										"disabled": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
									},
								},
								"destinations": schema.ListNestedBlock{
									MarkdownDescription: "Destination Origin pools (clusters). When requests have to distributed among multiple upstream clusters, multiple destinations are configured, each having its own cluster and weight. Traffic is distributed among clusters based on the weight configured. destinations: - cluster: - kind: ves.io.vega.cfg.adc.cluster.Object uid: cluster-1 weight: 20 - cluster: - kind: ves.io.vega.cfg.adc.cluster.Object uid: cluster-2 weight: 30 - cluster: - kind: ves.io.vega.cfg.adc.cluster.Object uid: cluster-3 weight: 50 This indicates that out of every 100 requests, 50 goes to cluster-3, 30 to cluster-2 and 20 to cluster-1 When single destination is configured, weight is ignored. All the requests are sent to the cluster specified in the destination",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"priority": schema.Int64Attribute{
												MarkdownDescription: "Priority. Priority of this cluster, valid only with multiple destinations are configured. Value of 0 will make the cluster as lowest priority upstream cluster Priority of 1 means highest priority and is considered active. When active cluster is not available, lower priority clusters are made active as per the increasing priority.",
												Optional: true,
											},
											"weight": schema.Int64Attribute{
												MarkdownDescription: "Weight. When requests have to distributed among multiple upstream clusters, multiple destinations are configured, each having its own cluster and weight. Traffic is distributed among clusters based on the weight configured. destinations: - cluster: - kind: ves.io.vega.cfg.adc.cluster.Object uid: cluster-1 weight: 20 - cluster: - kind: ves.io.vega.cfg.adc.cluster.Object uid: cluster-2 weight: 30 - cluster: - kind: ves.io.vega.cfg.adc.cluster.Object uid: cluster-3 weight: 10 This indicates that out of every 60 requests, 10 goes to cluster-3, 30 to cluster-2 and 20 to cluster-1 When single destination is configured, weight is ignored. All the requests are sent to the cluster specified in the destination",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"cluster": schema.ListNestedBlock{
												MarkdownDescription: "Cluster. Indicates the upstream cluster to which the request should be sent. If the cluster does not exist ServiceUnavailable response will be sent",
												NestedObject: schema.NestedBlockObject{
													Attributes: map[string]schema.Attribute{},
												},
											},
											"endpoint_subsets": schema.SingleNestedBlock{
												MarkdownDescription: "Endpoint Subsets. Upstream cluster may be configured to divide its endpoints into subsets based on metadata attached to the endpoints. Routes may then specify the metadata that a endpoint must match in order to be selected by the load balancer Labels field of endpoint object's metadata is used for subset matching. For endpoints which are discovered in K8S or Consul cluster, the label of the service is merged with endpoint's labels. In case of Consul, the label is derived from the 'Tag' field. For labels that are common between configured endpoint and discovered service, labels from discovered service takes precedence. List of key-value pairs that will be used as matching metadata. Only those endpoints of upstream cluster which match this metadata will be selected for load balancing",
											},
										},
									},
								},
								"do_not_retract_cluster": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"endpoint_subsets": schema.SingleNestedBlock{
									MarkdownDescription: "Endpoint Subsets. Upstream cluster may be configured to divide its endpoints into subsets based on metadata attached to the endpoints. Routes may then specify the metadata that a endpoint must match in order to be selected by the load balancer Labels field of endpoint object's metadata is used for subset matching. For endpoint's which are discovered in K8S or Consul cluster, the label of the service is merged with endpoint's labels. In case of Consul, the label is derived from the 'Tag' field. For labels that are common between configured endpoint and discovered service, labels from discovered service takes precedence. List of key-value pairs that will be used as matching metadata. Only those endpoints of upstream cluster which match this metadata will be selected for load balancing",
								},
								"hash_policy": schema.ListNestedBlock{
									MarkdownDescription: "Hash Policy. Specifies a list of hash policies to use for ring hash load balancing. Each hash policy is evaluated individually and the combined result is used to route the request",
									NestedObject: schema.NestedBlockObject{
										Attributes: map[string]schema.Attribute{
											"header_name": schema.StringAttribute{
												MarkdownDescription: "Header Name. The name or key of the request header that will be used to obtain the hash key",
												Optional: true,
											},
											"source_ip": schema.BoolAttribute{
												MarkdownDescription: "Source IP. Hash based on source IP address",
												Optional: true,
											},
											"terminal": schema.BoolAttribute{
												MarkdownDescription: "Terminal. Specify if its a terminal policy",
												Optional: true,
											},
										},
										Blocks: map[string]schema.Block{
											"cookie": schema.SingleNestedBlock{
												MarkdownDescription: "Hashing using Cookie. Two types of cookie affinity: 1. Passive. Takes a cookie that's present in the cookies header and hashes on its value. 2. Generated. Generates and sets a cookie with an expiration (TTL) on the first request from the client in its response to the client, based on the endpoint the request gets sent to. The client then presents this on the next and all subsequent requests. The hash of this is sufficient to ensure these requests get sent to the same endpoint. The cookie is generated by hashing the source and destination ports and addresses so that multiple independent HTTP2 streams on the same connection will independently receive the same cookie, even if they arrive simultaneously.",
											},
										},
									},
								},
								"mirror_policy": schema.SingleNestedBlock{
									MarkdownDescription: "Mirror Policy. MirrorPolicy is used for shadowing traffic from one cluster to another. The approach used is 'fire and forget', meaning it will not wait for the shadow cluster to respond before returning the response from the primary cluster. All normal statistics are collected for the shadow cluster making this feature useful for testing and troubleshooting.",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"cluster": schema.ListNestedBlock{
											MarkdownDescription: "Mirror Destination Cluster. Specifies the cluster to which the requests will be mirrored. The cluster object referred here must be present.",
											NestedObject: schema.NestedBlockObject{
												Attributes: map[string]schema.Attribute{},
											},
										},
										"percent": schema.SingleNestedBlock{
											MarkdownDescription: "Fractional Percent. Fraction used where sampling percentages are needed. example sampled requests",
										},
									},
								},
								"query_params": schema.SingleNestedBlock{
									MarkdownDescription: "Query Parameters. Handling of incoming query parameters in simple route.",
									Attributes: map[string]schema.Attribute{
										"replace_params": schema.StringAttribute{
											MarkdownDescription: "Replace All Parameters.",
											Optional: true,
										},
									},
									Blocks: map[string]schema.Block{
										"remove_all_params": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
										"retain_all_params": schema.SingleNestedBlock{
											MarkdownDescription: "Empty. This can be used for messages where no values are needed",
										},
									},
								},
								"regex_rewrite": schema.SingleNestedBlock{
									MarkdownDescription: "Regex Match Rewrite. RegexMatchRewrite describes how to match a string and then produce a new string using a regular expression and a substitution string.",
									Attributes: map[string]schema.Attribute{
										"pattern": schema.StringAttribute{
											MarkdownDescription: "Pattern. The regular expression used to find portions of a string that should be replaced.",
											Optional: true,
										},
										"substitution": schema.StringAttribute{
											MarkdownDescription: "Substitution. The string that should be substituted into matching portions of the subject string during a substitution operation to produce a new string.",
											Optional: true,
										},
									},
								},
								"retract_cluster": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"retry_policy": schema.SingleNestedBlock{
									MarkdownDescription: "Retry Policy. Retry policy configuration for route destination.",
									Attributes: map[string]schema.Attribute{
										"num_retries": schema.Int64Attribute{
											MarkdownDescription: "Number of Retries. Specifies the allowed number of retries. Defaults to 1. Retries can be done any number of times. An exponential back-off algorithm is used between each retry",
											Optional: true,
										},
										"per_try_timeout": schema.Int64Attribute{
											MarkdownDescription: "Per Try Timeout. Specifies a non-zero timeout per retry attempt. In milliseconds",
											Optional: true,
										},
										"retriable_status_codes": schema.ListAttribute{
											MarkdownDescription: "Status Code to Retry. HTTP status codes that should trigger a retry in addition to those specified by retry_on.",
											Optional: true,
											ElementType: types.StringType,
										},
										"retry_condition": schema.ListAttribute{
											MarkdownDescription: "Retry Condition. Specifies the conditions under which retry takes place. Retries can be on different types of condition depending on application requirements. For example, network failure, all 5xx response codes, idempotent 4xx response codes, etc The possible values are '5xx' : Retry will be done if the upstream server responds with any 5xx response code, or does not respond at all (disconnect/reset/read timeout). 'gateway-error' : Retry will be done only if the upstream server responds with 502, 503 or 504 responses (Included in 5xx) 'connect-failure' : Retry will be done if the request fails because of a connection failure to the upstream server (connect timeout, etc.). (Included in 5xx) 'refused-stream' : Retry is done if the upstream server resets the stream with a REFUSED_STREAM error code (Included in 5xx) 'retriable-4xx' : Retry is done if the upstream server responds with a retriable 4xx response code. The only response code in this category is HTTP CONFLICT (409) 'retriable-status-codes' : Retry is done if the upstream server responds with any response code matching one defined in retriable_status_codes field 'reset' : Retry is done if the upstream server does not respond at all (disconnect/reset/read timeout.)",
											Optional: true,
											ElementType: types.StringType,
										},
									},
									Blocks: map[string]schema.Block{
										"back_off": schema.SingleNestedBlock{
											MarkdownDescription: "Retry BackOff Interval. Specifies parameters that control retry back off.",
										},
									},
								},
								"spdy_config": schema.SingleNestedBlock{
									MarkdownDescription: "SPDY Configuration. Request headers of such upgrade looks like below 'connection', 'Upgrade' 'upgrade', 'SPDY/3.1' Configuration to allow UPGRADE of connection to SPDY and any additional tuning With configuration to allow SPDY upgrade, ADC will produce following response 'HTTP/1.1 101 Switching Protocols 'Upgrade': 'SPDY/3.1' 'Connection': 'Upgrade'",
									Attributes: map[string]schema.Attribute{
										"use_spdy": schema.BoolAttribute{
											MarkdownDescription: "Use SPDY. Specifies that the HTTP client connection to this route is allowed to upgrade to a SPDY connection",
											Optional: true,
										},
									},
								},
								"web_socket_config": schema.SingleNestedBlock{
									MarkdownDescription: "Websocket Configuration. Configuration to allow Websocket Request headers of such upgrade looks like below 'connection', 'Upgrade' 'upgrade', 'websocket' With configuration to allow websocket upgrade, ADC will produce following response 'HTTP/1.1 101 Switching Protocols 'Upgrade': 'websocket' 'Connection': 'Upgrade'",
									Attributes: map[string]schema.Attribute{
										"use_websocket": schema.BoolAttribute{
											MarkdownDescription: "Use Websocket. Specifies that the HTTP client connection to this route is allowed to upgrade to a WebSocket connection",
											Optional: true,
										},
									},
								},
							},
						},
						"route_direct_response": schema.SingleNestedBlock{
							MarkdownDescription: "Direct Response. Send this direct response in case of route match action is direct response",
							Attributes: map[string]schema.Attribute{
								"response_body_encoded": schema.StringAttribute{
									MarkdownDescription: "Response Body. Response body to send. Currently supported URL schemes is string:/// for which message should be encoded in Base64 format. The message can be either plain text or html. E.g. '<p> Access Denied </p>'. Base64 encoded string url for this is string:///PHA+IEFjY2VzcyBEZW5pZWQgPC9wPg==",
									Optional: true,
								},
								"response_code": schema.Int64Attribute{
									MarkdownDescription: "Response Code. response code to send",
									Optional: true,
								},
							},
						},
						"route_redirect": schema.SingleNestedBlock{
							MarkdownDescription: "Redirect. route redirect parameters when match action is redirect.",
							Attributes: map[string]schema.Attribute{
								"host_redirect": schema.StringAttribute{
									MarkdownDescription: "Host. swap host part of incoming URL in redirect URL",
									Optional: true,
								},
								"path_redirect": schema.StringAttribute{
									MarkdownDescription: "Path. swap path part of incoming URL in redirect URL",
									Optional: true,
								},
								"prefix_rewrite": schema.StringAttribute{
									MarkdownDescription: "Prefix Rewrite. In Redirect response, the matched prefix (or path) should be swapped with this value. This option allows redirect URLs be dynamically created based on the request",
									Optional: true,
								},
								"proto_redirect": schema.StringAttribute{
									MarkdownDescription: "Protocol. swap protocol part of incoming URL in redirect URL The protocol can be swapped with either http or https When incoming-proto option is specified, swapping of protocol is not done.",
									Optional: true,
								},
								"replace_params": schema.StringAttribute{
									MarkdownDescription: "Replace All Parameters.",
									Optional: true,
								},
								"response_code": schema.Int64Attribute{
									MarkdownDescription: "Response Code. The HTTP status code to use in the redirect response.",
									Optional: true,
								},
							},
							Blocks: map[string]schema.Block{
								"remove_all_params": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"retain_all_params": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
							},
						},
						"service_policy": schema.SingleNestedBlock{
							MarkdownDescription: "Service Policy Configuration. ServicePolicy configuration details at route level",
							Attributes: map[string]schema.Attribute{
								"disable": schema.BoolAttribute{
									MarkdownDescription: "Disable. disable service policy at route level, if it is configured at virtual-host level",
									Optional: true,
								},
							},
						},
						"waf_exclusion_policy": schema.SingleNestedBlock{
							MarkdownDescription: "Object reference. This type establishes a direct reference from one object(the referrer) to another(the referred). Such a reference is in form of tenant/namespace/name",
							Attributes: map[string]schema.Attribute{
								"name": schema.StringAttribute{
									MarkdownDescription: "Name. When a configuration object(e.g. virtual_host) refers to another(e.g route) then name will hold the referred object's(e.g. route's) name.",
									Optional: true,
								},
								"namespace": schema.StringAttribute{
									MarkdownDescription: "Namespace. When a configuration object(e.g. virtual_host) refers to another(e.g route) then namespace will hold the referred object's(e.g. route's) namespace.",
									Optional: true,
								},
								"tenant": schema.StringAttribute{
									MarkdownDescription: "Tenant. When a configuration object(e.g. virtual_host) refers to another(e.g route) then tenant will hold the referred object's(e.g. route's) tenant.",
									Optional: true,
								},
							},
						},
						"waf_type": schema.SingleNestedBlock{
							MarkdownDescription: "WAF Instance. WAF instance will be pointing to an app_firewall object",
							Attributes: map[string]schema.Attribute{
							},
							Blocks: map[string]schema.Block{
								"app_firewall": schema.SingleNestedBlock{
									MarkdownDescription: "App Firewall Reference. A list of references to the app_firewall configuration objects",
									Attributes: map[string]schema.Attribute{
									},
									Blocks: map[string]schema.Block{
										"app_firewall": schema.ListNestedBlock{
											MarkdownDescription: "Application Firewall. References to an Application Firewall configuration object",
											NestedObject: schema.NestedBlockObject{
												Attributes: map[string]schema.Attribute{},
											},
										},
									},
								},
								"disable_waf": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
								"inherit_waf": schema.SingleNestedBlock{
									MarkdownDescription: "Empty. This can be used for messages where no values are needed",
								},
							},
						},
					},

				},
			},
		},
	}
}

func (r *RouteResource) Configure(ctx context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	client, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError(
			"Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData),
		)
		return
	}
	r.client = client
}

// ValidateConfig implements resource.ResourceWithValidateConfig
func (r *RouteResource) ValidateConfig(ctx context.Context, req resource.ValidateConfigRequest, resp *resource.ValidateConfigResponse) {
	var data RouteResourceModel
	resp.Diagnostics.Append(req.Config.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}
}

// ModifyPlan implements resource.ResourceWithModifyPlan
func (r *RouteResource) ModifyPlan(ctx context.Context, req resource.ModifyPlanRequest, resp *resource.ModifyPlanResponse) {
	if req.Plan.Raw.IsNull() {
		resp.Diagnostics.AddWarning(
			"Resource Destruction",
			"This will permanently delete the route from F5 Distributed Cloud.",
		)
		return
	}

	if req.State.Raw.IsNull() {
		var plan RouteResourceModel
		resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
		if resp.Diagnostics.HasError() {
			return
		}

		if plan.Name.IsUnknown() {
			resp.Diagnostics.AddWarning(
				"Unknown Resource Name",
				"The resource name is not yet known. This may affect planning for dependent resources.",
			)
		}
	}
}

// UpgradeState implements resource.ResourceWithUpgradeState
func (r *RouteResource) UpgradeState(ctx context.Context) map[int64]resource.StateUpgrader {
	return map[int64]resource.StateUpgrader{
		0: {
			PriorSchema: &schema.Schema{
				Attributes: map[string]schema.Attribute{
					"name":        schema.StringAttribute{Required: true},
					"namespace":   schema.StringAttribute{Required: true},
					"annotations": schema.MapAttribute{Optional: true, ElementType: types.StringType},
					"labels":      schema.MapAttribute{Optional: true, ElementType: types.StringType},
					"id":          schema.StringAttribute{Computed: true},
				},
			},
			StateUpgrader: func(ctx context.Context, req resource.UpgradeStateRequest, resp *resource.UpgradeStateResponse) {
				var priorState struct {
					Name        types.String `tfsdk:"name"`
					Namespace   types.String `tfsdk:"namespace"`
					Annotations types.Map    `tfsdk:"annotations"`
					Labels      types.Map    `tfsdk:"labels"`
					ID          types.String `tfsdk:"id"`
				}

				resp.Diagnostics.Append(req.State.Get(ctx, &priorState)...)
				if resp.Diagnostics.HasError() {
					return
				}

				upgradedState := RouteResourceModel{
					Name:        priorState.Name,
					Namespace:   priorState.Namespace,
					Annotations: priorState.Annotations,
					Labels:      priorState.Labels,
					ID:          priorState.ID,
					Timeouts:    timeouts.Value{},
				}

				resp.Diagnostics.Append(resp.State.Set(ctx, upgradedState)...)
			},
		},
	}
}

func (r *RouteResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var data RouteResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	createTimeout, diags := data.Timeouts.Create(ctx, inttimeouts.DefaultCreate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, createTimeout)
	defer cancel()

	tflog.Debug(ctx, "Creating route", map[string]interface{}{
		"name":      data.Name.ValueString(),
		"namespace": data.Namespace.ValueString(),
	})

	apiResource := &client.Route{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.RouteSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	created, err := r.client.CreateRoute(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to create Route: %s", err))
		return
	}

	data.ID = types.StringValue(created.Metadata.Name)

	psd := privatestate.NewPrivateStateData()
	psd.SetUID(created.Metadata.UID)
	resp.Diagnostics.Append(psd.SaveToPrivateState(ctx, resp)...)

	tflog.Trace(ctx, "created Route resource")
	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RouteResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var data RouteResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	readTimeout, diags := data.Timeouts.Read(ctx, inttimeouts.DefaultRead)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, readTimeout)
	defer cancel()

	psd, psDiags := privatestate.LoadFromPrivateState(ctx, &req)
	resp.Diagnostics.Append(psDiags...)

	apiResource, err := r.client.GetRoute(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to read Route: %s", err))
		return
	}

	if psd != nil && psd.Metadata.UID != "" && apiResource.Metadata.UID != psd.Metadata.UID {
		resp.Diagnostics.AddWarning(
			"Resource Drift Detected",
			"The route may have been recreated outside of Terraform.",
		)
	}

	data.ID = types.StringValue(apiResource.Metadata.Name)
	data.Name = types.StringValue(apiResource.Metadata.Name)
	data.Namespace = types.StringValue(apiResource.Metadata.Namespace)

	if len(apiResource.Metadata.Labels) > 0 {
		labels, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Labels)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Labels = labels
		}
	} else {
		data.Labels = types.MapNull(types.StringType)
	}

	if len(apiResource.Metadata.Annotations) > 0 {
		annotations, diags := types.MapValueFrom(ctx, types.StringType, apiResource.Metadata.Annotations)
		resp.Diagnostics.Append(diags...)
		if !resp.Diagnostics.HasError() {
			data.Annotations = annotations
		}
	} else {
		data.Annotations = types.MapNull(types.StringType)
	}

	psd = privatestate.NewPrivateStateData()
	psd.SetUID(apiResource.Metadata.UID)
	resp.Diagnostics.Append(psd.SaveToPrivateState(ctx, resp)...)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RouteResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var data RouteResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	updateTimeout, diags := data.Timeouts.Update(ctx, inttimeouts.DefaultUpdate)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, updateTimeout)
	defer cancel()

	apiResource := &client.Route{
		Metadata: client.Metadata{
			Name:      data.Name.ValueString(),
			Namespace: data.Namespace.ValueString(),
		},
		Spec: client.RouteSpec{},
	}

	if !data.Labels.IsNull() {
		labels := make(map[string]string)
		resp.Diagnostics.Append(data.Labels.ElementsAs(ctx, &labels, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Labels = labels
	}

	if !data.Annotations.IsNull() {
		annotations := make(map[string]string)
		resp.Diagnostics.Append(data.Annotations.ElementsAs(ctx, &annotations, false)...)
		if resp.Diagnostics.HasError() {
			return
		}
		apiResource.Metadata.Annotations = annotations
	}

	updated, err := r.client.UpdateRoute(ctx, apiResource)
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to update Route: %s", err))
		return
	}

	data.ID = types.StringValue(updated.Metadata.Name)

	psd := privatestate.NewPrivateStateData()
	psd.SetUID(updated.Metadata.UID)
	resp.Diagnostics.Append(psd.SaveToPrivateState(ctx, resp)...)

	resp.Diagnostics.Append(resp.State.Set(ctx, &data)...)
}

func (r *RouteResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var data RouteResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &data)...)
	if resp.Diagnostics.HasError() {
		return
	}

	deleteTimeout, diags := data.Timeouts.Delete(ctx, inttimeouts.DefaultDelete)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	ctx, cancel := context.WithTimeout(ctx, deleteTimeout)
	defer cancel()

	err := r.client.DeleteRoute(ctx, data.Namespace.ValueString(), data.Name.ValueString())
	if err != nil {
		resp.Diagnostics.AddError("Client Error", fmt.Sprintf("Unable to delete Route: %s", err))
		return
	}
}

func (r *RouteResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
